<h2>Affair</h2>
<ul class="list_affair">
    <li class="affair_item01">
	<h3>Magie Lust und Entspannung</h3>
	<a href="#" class="affair_pic" title="Magie Lust und Entspannung">Hier klicken</a>
    </li>
    <li class="affair_item01">
	<h3>Sündig wie die Hölle</h3>
	<a href="#" class="affair_pic" title="Sündig wie die Hölle">Hier klicken</a>
    </li>
    <li class="affair_item01">
	<h3>Raum der bizarren Lust</h3>
	<a href="#" class="affair_pic" title="Raum der bizarren Lust">Hier klicken</a>
    </li>
    <li class="affair_item01">
	<h3>In den Tiefen des Wassers</h3>
	<a href="#" class="affair_pic" title="In den Tiefen des Wassers">Hier klicken</a>
    </li>
</ul>
