<!--[if lt IE 9]><div id="footer" class="footer clear_fix><![endif]-->
<footer id="footer" class="footer clear_fix">
	<!--[if lt IE 9]><div class="wrapper"><![endif]-->
	<section class="wrapper">
		<?php extras('footer'); ?>
	</section>
	<!--[if lt IE 9]></div><![endif]-->
</footer>
<!--[if lt IE 9]></div><div id="bottom" class="bottom"><![endif]-->
<section id="bottom" class="bottom">
	<!--[if lt IE 9]><div class="wrapper"><![endif]-->
	<section class="wrapper">
		<?php echo l('powered_by') . ' ' . anchor_element('external', '', 'js_backlink', l('redaxscript'), l('redaxscript_website')) . ' ' . l('redaxscript_version'); ?>
	</section>
	<!--[if lt IE 9]></div><![endif]-->
</section>
<!--[if lt IE 9]></div><![endif]-->