<!--[if lt IE 9]><div id="header" class="header wrapper clear_fix"><![endif]-->
<header id="header" class="header wrapper clear_fix">
	<?php if (DB_CONNECTED == 1): ?>
		<?php if (s('title')): ?>
			<h1 class="title_website"><?php echo anchor_element('', '', '', s('title'), ROOT); ?></h1>
		<?php endif; ?>
		<?php if (s('description')): ?>
			<p class="description_website"><?php echo s('description'); ?></p>
		<?php endif; ?>
	<?php endif; ?>
</header>
<!--[if lt IE 9]></div><![endif]-->