<?php namespace Redaxscript; ?>

<!DOCTYPE html>
<html lang="<?php echo Registry::get('language'); ?>" class="<?php echo Template::helperClass(); ?>">

	<!-- head -->

	<head>
		<?php echo Template::partial(array(
			'templates/scratch/head.phtml',
			'templates/admin/head.phtml'
		)); ?>
	</head>

	<!-- body -->

	<body class="wrapper_body">

		<!-- admin panel and header -->

		<?php echo Template::partial(array(
			'templates/admin/panel.phtml',
			'templates/scratch/header.phtml'
		)); ?>

		<!-- main -->

		<div class="wrapper clearfix">
			<?php echo Template::partial(array(
				'templates/scratch/content.phtml',
				'templates/scratch/sidebar.phtml'
			)); ?>
		</div>

		<!-- footer -->

		<?php echo Template::partial('templates/scratch/footer.phtml'); ?>
		<?php echo Template::script(); ?>
	</body>
</html>