<!--[if lt IE 9]><div id="footer" class="footer wrapper"><![endif]-->
<footer id="footer" class="footer">
	<!--[if lt IE 9]><div class="wrapper"><![endif]-->
	<section class="wrapper">
		<?php echo l('powered_by') . ' ' . anchor_element('external', '', 'link_powered_by', l('redaxscript'), l('redaxscript_website')) . ' ' . l('redaxscript_version'); ?>
	</section>
	<!--[if lt IE 9]></div><![endif]-->
</footer>
<!--[if lt IE 9]></div><![endif]-->