<!--[if lt IE 9]><div id="header" class="header"><![endif]-->
<header id="header" class="header">
	<!--[if lt IE 9]><div class="wrapper wrapper_header"><![endif]-->
	<section class="wrapper">
		<?php if (DB_CONNECTED == 1): ?>
			<?php navigation_list('categories', array(
				'class' => 'list_header',
				'limit' => 10
			)); ?>
		<?php endif; ?>
	</section>
	<!--[if lt IE 9]></div><![endif]-->
</header>
<!--[if lt IE 9]></div><![endif]-->