<?php namespace Redaxscript; ?>

<!DOCTYPE html>
<html lang="<?php echo Registry::get('language'); ?>" class="<?php echo Template::helperClass(); ?>">

	<!-- head -->

	<head>

		<!-- template head -->

		<?php include_once('head.phtml'); ?>

		<!-- admin head -->

		<?php include_once('templates/admin/head.phtml'); ?>
	</head>

	<!-- body -->

	<body class="wrapper_body">

		<!-- admin panel -->

		<?php include_once('templates/admin/panel.phtml'); ?>

		<!-- header -->

		<?php include_once('header.phtml'); ?>

		<!-- main -->

		<div class="wrapper clearfix">
			<?php include_once('sidebar.phtml'); ?>
			<?php include_once('content.phtml'); ?>
		</div>

		<!-- footer -->

		<?php include_once('footer.phtml'); ?>
		<?php scripts(); ?>
	</body>
</html>