<footer id="footer" class="footer">
	<section class="wrapper">
		<?php if (DB_CONNECTED == 1): ?>
			<?php navigation_list('categories', array(
				'class' => 'list_footer',
				'limit' => 15
			)); ?>
		<?php endif; ?>
		<span class="text_footer">
			<?php echo l('powered_by') . ' ' . anchor_element('external', '', 'link_powered_by', l('redaxscript'), l('redaxscript_website')) . ' ' . l('redaxscript_version'); ?>
			<span class="divider"><?php echo s('divider'); ?></span>
			Design by <?php echo anchor_element('external', '', 'link_made_by', 'Jörg Steinhauer', 'joergsteinhauer.net'); ?>
		</span>
	</section>
</footer>