<?php namespace Redaxscript; ?>

<header id="header" class="header">
	<section class="wrapper">

		<!-- website branding -->

		<?php if (Db::getSettings('title')): ?>
			<h1 class="title_website">
				<a href="<?php Registry::get('root'); ?>"><?php echo Db::getSettings('title'); ?></a>
			</h1>
		<?php endif; ?>

		<!-- dropdown -->

		<?php navigation_list('categories', array(
			'children' => 1,
			'class' => 'js_dropdown list_dropdown list_header',
			'limit' => 5
		)); ?>
	</section>
</header>