<?php use Redaxscript\Template as Template; ?>

<header id="header" class="header">
	<section class="wrapper">

		<!-- website branding -->

		<?php if (Template::setting('title')): ?>
			<h1 class="title_website">
				<a href="<?php echo Template::registry('root'); ?>"><?php echo Template::setting('title'); ?></a>
			</h1>
		<?php endif; ?>

		<!-- dropdown -->

		<?php echo Template::navigation('categories', array(
			'children' => 1,
			'class' => 'js_dropdown list_dropdown list_header',
			'limit' => 5
		)); ?>
	</section>
</header>