<?php namespace Redaxscript; ?>

<!-- base and title -->

<?php echo Template::base(); ?>
<?php echo Template::title(); ?>

<!-- meta -->

<?php echo Template::meta(); ?>
<meta name="viewport" content="width=device-width" />

<!-- link -->

<?php echo Template::link(); ?>
<?php if (!Registry::get('myMobile')): ?>
	<link href="//fonts.googleapis.com/css?family=Marmelad&amp;subset=<?php echo Template::helperSubset(); ?>" rel="stylesheet" />
<?php endif; ?>

<!-- style and script -->

<?php echo Template::style(); ?>
<?php echo Template::script('init'); ?>