<!DOCTYPE html>
<html lang="<?php echo LANGUAGE; ?>" class="<?php helper_class(); ?>">
	<head>
		<?php head(); ?>
		<meta name="viewport" content="width=device-width" />
		<?php scripts('startup'); ?>
		<?php styles(); ?>
		<?php if (MY_MOBILE == ''): ?>
			<link type="text/css" href="http://fonts.googleapis.com/css?family=Marmelad&amp;subset=<?php helper_subset(); ?>" rel="stylesheet" />
		<?php endif; ?>
		<?php if (LOGGED_IN == TOKEN && FIRST_PARAMETER != 'logout'): ?>
			<?php include_once('templates/admin/head.phtml'); ?>
		<?php endif; ?>
	</head>
	<body class="wrapper_body">
		<?php if (LOGGED_IN == TOKEN && FIRST_PARAMETER != 'logout'): ?>
			<?php include_once('templates/admin/panel.phtml'); ?>
		<?php endif; ?>
		<?php include_once('header.phtml'); ?>
		<div class="wrapper clear_fix">
			<?php include_once('content.phtml'); ?>
			<?php include_once('sidebar.phtml'); ?>
		</div>
		<?php include_once('footer.phtml'); ?>
		<?php scripts(); ?>
	</body>
</html>