<p class="rs-admin-text-documentation">Syntax for your content:</p>

<pre class="rs-admin-js-code rs-admin-code-default"><?php echo htmlspecialchars('<rs-module>'); ?>
{
	"LightGallery":
	{
		"directory": "images/gallery",
		"options":
		{
			"quality": 80,
			"height": 200
		}
	}
}
<?php echo htmlspecialchars('</rs-module>'); ?></pre>

<p class="rs-admin-text-documentation">Syntax to create thumbs on each page refresh with reversed order:</p>

<pre class="rs-admin-js-code rs-admin-code-default"><?php echo htmlspecialchars('<rs-module>'); ?>
{
	"LightGallery":
	{
		"directory": "images/gallery",
		"options":
		{
			"order": "desc",
			"command": "create"
		}
	}
}
<?php echo htmlspecialchars('</rs-module>'); ?></pre>

<p class="rs-admin-text-documentation">Syntax to remove thumbs:</p>

<pre class="rs-admin-js-code rs-admin-code-default"><?php echo htmlspecialchars('<rs-module>'); ?>
{
	"LightGallery":
	{
		"directory": "images/gallery",
		"options":
		{
			"command": "remove"
		}
	}
}
<?php echo htmlspecialchars('</rs-module>'); ?></pre>
