<p>Syntax for your content.</p>

<code class="js_code_quote box_code">&lt;module&gt;
{
	"LazyLoad":
	{
		"src": "images/redaxscript.png",
		"options":
		{
			"class": "image image_default",
			"alt": "Alternative text for image"
		}
	}
}
&lt;/module&gt;</code>

<p>Syntax to multiserve images according to device.</p>

<code class="js_code_quote box_code">&lt;module&gt;
{
	"LazyLoad":
	{
		"src":
		{
			"desktop": "images/redaxscript_desktop.png",
			"tablet": "images/redaxscript_tablet.png",
			"mobile": "images/redaxscript_mobile.png"
		}
	}
}
&lt;/module&gt;</code>