<h3 class="title_content_sub">.js_accordion (div > div > h3 + div)</h3>

<div class="js_accordion">
	<div class="js_set_accordion js_set_active set_accordion set_accordion_default set_active">
		<h3 class="js_title_accordion js_title_active title_accordion title_accordion_default title_active">
			<?php echo l('1', '_number'); ?>
		</h3>
		<div class="js_box_accordion js_box_active box_accordion box_accordion_default box_active">
			<?php echo l('1', '_number'); ?>
		</div>
	</div>
	<div class="js_set_accordion set_accordion set_accordion_default">
		<h3 class="js_title_accordion title_accordion title_accordion_default">
			<?php echo l('2', '_number'); ?>
		</h3>
		<div class="js_box_accordion box_accordion box_accordion_default">
			<?php echo l('2', '_number'); ?>
		</div>
	</div>
	<div class="js_set_accordion set_accordion set_accordion_default set_accordion_last">
		<h3 class="js_title_accordion title_accordion title_accordion_default">
			<?php echo l('3', '_number'); ?>
		</h3>
		<div class="js_box_accordion box_accordion box_accordion_default">
			<?php echo l('3', '_number'); ?>
		</div>
	</div>
</div>


<h3 class="title_content_sub">.js_accordion (form > fieldset > legend + ul)</h3>

<form class="js_accordion">
	<fieldset class="js_set_accordion set_accordion set_accordion_default">
		<legend class="js_title_accordion title_accordion title_accordion_default">
			<?php echo l('4', '_number'); ?>
		</legend>
		<ul class="js_box_accordion box_accordion box_accordion_default">
			<li>
				<?php echo l('4', '_number'); ?>
			</li>
		</ul>
	</fieldset>
	<fieldset class="js_set_accordion js_set_active set_accordion set_accordion_default set_active">
		<legend class="js_title_accordion js_title_active title_accordion title_accordion_default title_active">
			<?php echo l('5', '_number'); ?>
		</legend>
		<ul class="js_box_accordion js_box_active box_accordion box_accordion_default box_active">
			<li>
				<?php echo l('5', '_number'); ?>
			</li>
		</ul>
	</fieldset>
	<fieldset class="js_set_accordion set_accordion set_accordion_default set_accordion_last">
		<legend class="js_title_accordion title_accordion title_accordion_default">
			<?php echo l('6', '_number'); ?>
		</legend>
		<ul class="js_box_accordion box_accordion box_accordion_default">
			<li>
				<?php echo l('6', '_number'); ?>
			</li>
		</ul>
	</fieldset>
</form>

