<?php
namespace Redaxscript;

$language = Language::getInstance();
$element = new Html\Element();
$inputElement = $element
	->copy()
	->init('input',
	[
		'class' => $admin ? 'rs-admin-fn-status-accordion' : 'rs-fn-status-accordion',
		'type' => 'radio',
		'name' => $admin ? 'Modules\Preview\Admin\Accordion' : 'Modules\Preview\Accordion'
	]);
$labelElement = $element
	->copy()
	->init('label',
	[
		'class' => $admin ? 'rs-admin-fn-toggle-accordion rs-admin-label-accordion' : 'rs-fn-toggle-accordion rs-label-accordion'
	]);
$boxElement = $element
	->copy()
	->init('div',
	[
		'class' => $admin ? 'rs-admin-fn-content-accordion rs-admin-box-accordion' : 'rs-fn-content-accordion rs-box-accordion'
	]);
?>

<!-- accordion -->

<div class="<?php echo $admin ? 'rs-admin-component-accordion' : 'rs-component-accordion'; ?>">

	<?php for ($i = 1; $i < 6; $i++): ?>

		<?php echo $inputElement
						->copy()
						->attr('id', $admin ? 'Modules\Preview\Admin\Accordion\\' . $i : 'Modules\Preview\Accordion\\' . $i)
						->attr('checked', $i === 1 ? 'checked' : null)
						->text($language->get('_number')[$i]) .
					$labelElement
						->copy()
						->attr('for', $admin ? 'Modules\Preview\Admin\Accordion\\' . $i : 'Modules\Preview\Accordion\\' . $i)
						->text($language->get('_number')[$i]) .
					$boxElement
						->copy()
						->text($language->get('_number')[$i]); ?>

	<?php endfor; ?>

</div>
