<?php
namespace Redaxscript;

$titlePartialElement = new Element('h3', array(
	'class' => 'title_content_sub'
));
$setAccordionElement = new Element('div', array(
	'class' => 'js_set_accordion set_accordion set_accordion_default'
));
$titleAccordionElement = new Element('h3', array(
	'class' => 'js_title_accordion title_accordion title_accordion_default'
));
$boxAccordionElement = new Element('div', array(
	'class' => 'js_box_accordion box_accordion box_accordion_default'
));
?>

<?php echo $titlePartialElement->text('.js_accordion (div > h3 + div)'); ?>

<div class="js_accordion">

	<!-- active -->

	<?php echo $setAccordionElement
		->copy()
		->addClass('js_set_active set_active')
		->html(
			$titleAccordionElement
				->copy()
				->addClass('js_title_active title_active')
				->text(Language::get(1, '_number')) .
			$boxAccordionElement
				->copy()
				->addClass('js_box_active box_active')
				->text(Language::get(1, '_number'))
		);
	?>

	<!-- inactive -->

	<?php echo $setAccordionElement->html(
		$titleAccordionElement->text(Language::get(2, '_number')) .
		$boxAccordionElement->text(Language::get(2, '_number'))
	); ?>

	<!-- inactive -->

	<?php echo $setAccordionElement->html(
		$titleAccordionElement->text(Language::get(3, '_number')) .
		$boxAccordionElement->text(Language::get(3, '_number'))
	); ?>

</div>