<h2 class="title_content">Box</h2>


<h3 class="title_content_sub">.box_comment</h3>

<div class="box_comment"><?php echo l('preview_preview'); ?></div>


<h3 class="title_content_sub">.box_extra</h3>

<div class="box_extra"><?php echo l('preview_preview'); ?></div>


<h3 class="title_content_sub">.box_default</h3>

<div class="box_default"><?php echo l('preview_preview'); ?></div>


<h3 class="title_content_sub">.box_code</h3>

<div class="box_box_code"><?php echo l('preview_preview'); ?></div>

<?php

/* parser object */

$parser = new Redaxscript_Parser;

/* parse code */

echo $parser->getOutput('<code>
<?php

/**
 * check preview
 *
 * @return integer
 */

function check_preview()
{
	if (FIRST_PARAMETER == \'preview\')
	{
		$output = 1;
	}
	else
	{
		$output = 0;
	}
	return $output;
}
?>
</code>');
?>


<h3 class="title_content_sub">.box_infoline</h3>

<?php echo infoline('articles', '', MY_USER, NOW); ?>


<h3 class="title_content_sub">.box_quote</h3>

<blockquote class="box_quote">Redaxscript is an ultra lightweight CMS.</blockquote>

<p>Some text after .box_quote to demonstrate the spaces.</p>


<h3 class="title_content_sub">.box_line</h3>

<div class="box_line"></div>
