<?php
namespace Redaxscript;

$titlePartialElement = new Html\Element();
$titlePartialElement->init('h3', array(
	'class' => 'title_content_sub'
));
$boxElement = new Html\Element();
$boxElement->init('div')->text(Language::get('preview', '_preview'));
$boxArray = array(
	'box_comment',
	'box_extra',
	'box_default'
);
?>

<!-- several boxes -->

<?php foreach ($boxArray as $value): ?>

	<?php echo $titlePartialElement->text('.' . $value); ?>
	<?php echo $boxElement->copy()->addClass($value); ?>

<?php endforeach; ?>

<!-- box code -->

<?php echo $titlePartialElement->text('.js_code_quote box_code'); ?>

<?php echo $boxElement->copy()->addClass('js_code_quote box_code')->text('&lt;module&gt;
{
	"ModuleName":
	{
		"parameter": "value"
	}
}
&lt;/module&gt;'); ?>

<!-- box quote -->

<?php echo $titlePartialElement->text('.box_quote'); ?>

<blockquote class="box_quote">Ultra lightweight Content Management System for MySQL, PostgreSQL and SQLite.</blockquote>
<p>Placeholder text to demonstrate spacing.</p>

<!-- box line -->

<?php echo $titlePartialElement->text('.box_line'); ?>

<div class="box_line"></div>
