<h2 class="title_content">
	<?php if (SECOND_PARAMETER !== 'box'): ?>
		<a href="preview/box" title="Box">Box</a>
	<?php else: ?>
		Box
	<?php endif; ?>
</h2>


<h3 class="title_content_sub">.box_comment</h3>

<div class="box_comment"><?php echo l('preview', 'preview'); ?></div>


<h3 class="title_content_sub">.box_extra</h3>

<div class="box_extra"><?php echo l('preview', 'preview'); ?></div>


<h3 class="title_content_sub">.box_default</h3>

<div class="box_default"><?php echo l('preview', 'preview'); ?></div>


<h3 class="title_content_sub">.box_code</h3>

<div class="box_code">&lt;function&gt;
{
	"function_name":
	{
		"parameter": "value"
	}
}
&lt;/function&gt;</div>


<h3 class="title_content_sub">.box_infoline</h3>

<?php echo infoline('articles', '', MY_USER, NOW); ?>


<h3 class="title_content_sub">.box_quote</h3>

<blockquote class="box_quote">Redaxscript is an ultra lightweight CMS.</blockquote>

<p>Some text after .box_quote to demonstrate the spaces.</p>


<h3 class="title_content_sub">.box_line</h3>

<div class="box_line"></div>
