<?php
namespace Redaxscript;

$suffix = isset($admin) ? '' : '-default';
$prefix = isset($admin) ? 'admin-' : '';
$titlePartialElement = new Html\Element();
$titlePartialElement->init('h3', array(
	'class' => 'rs-title-preview-sub'
));
$buttonElement = new Html\Element();
$buttonElement
	->init('button', array(
		'class' => 'rs-' . $prefix . 'button' . $suffix
	))
	->text(Language::get('preview', '_preview'));
?>

<!-- button -->

<?php echo $titlePartialElement->text('.rs-' . $prefix . 'button' . $suffix); ?>

<?php echo $buttonElement; ?>

<!-- disabled -->

<?php echo $titlePartialElement->text('.rs-' . $prefix . 'button' . $suffix . '[disabled]'); ?>

<?php echo $buttonElement
	->copy()
	->attr('disabled', 'disabled'); ?>

<!-- large -->

<?php echo $titlePartialElement->text('.rs-' . $prefix . 'button' . $suffix . '.button-large'); ?>

<?php echo $buttonElement
	->copy()
	->addClass('rs-button-large'); ?>

<!-- disabled -->

<?php echo $titlePartialElement->text('.rs-' . $prefix . 'button' . $suffix . '.rs-button-large[disabled]'); ?>

<?php echo $buttonElement
	->copy()
	->addClass('rs-button-large')
	->attr('disabled', 'disabled'); ?>
