<?php
namespace Redaxscript;

$language = Language::getInstance();
$buttonElement = new Html\Element();
$buttonElement
	->init('button',
	[
		'class' => $admin ? 'rs-admin-button-default' : 'rs-button-default'
	])
	->text($language->get('_preview')['preview']);
?>

<!-- button -->

<?php echo $buttonElement; ?>

<!-- button disabled -->

<?php echo $buttonElement
	->copy()
	->attr('disabled', 'disabled'); ?>

<!-- button large -->

<?php echo $buttonElement
	->copy()
	->addClass($admin ? 'rs-admin-is-large' : 'rs-is-large'); ?>

