<?php
namespace Redaxscript;

$suffix = isset($admin) ? '_admin' : '_default';
$titlePartialElement = new Element('h3', array(
	'class' => 'title_content_sub'
));
$buttonElement = new Element('ul', array(
	'class' => 'button' . $suffix
));
$buttonElement->text(Language::get('preview', '_preview'));
?>

<!-- button -->

<?php echo $titlePartialElement->text('.button' . $suffix); ?>

<?php echo $buttonElement; ?>

<!-- disabled -->

<?php echo $titlePartialElement->text('.button' . $suffix . '[disabled]'); ?>

<?php echo $buttonElement
	->copy()
	->attr('disabled', 'disabled'); ?>

<!-- large -->

<?php echo $titlePartialElement->text('.button' . $suffix . '.button_large'); ?>

<?php echo $buttonElement
	->copy()
	->addClass('button_large'); ?>

<!-- disabled -->

<?php echo $titlePartialElement->text('.button' . $suffix . '.button_large[disabled]'); ?>

<?php echo $buttonElement
	->copy()
	->addClass('button_large')
	->attr('disabled', 'disabled'); ?>