<?php
namespace Redaxscript;

$titlePartialElement = new Element('h3', array(
	'class' => 'title_content_sub'
));
$buttonElement = new Element('a', array(
	'class' => 'js_confirm button_default'
));
?>

<!-- confirm -->

<?php echo $titlePartialElement->text('.js_confirm'); ?>

<?php echo $buttonElement
	->attr('href', Registry::get('rewriteRoute') . 'preview')
	->text(Language::get('confirm')); ?>