<?php
namespace Redaxscript;

$titlePartialElement = new Html\Element();
$titlePartialElement->init('h3', array(
	'class' => 'rs-title-preview-sub'
));
$buttonElement = new Html\Element();
$buttonElement->init('a', array(
	'class' => 'rs-js-confirm rs-button-default'
));
?>

<!-- confirm -->

<?php echo $titlePartialElement->text('.rs-js-confirm'); ?>

<?php echo $buttonElement
	->attr('href', Registry::get('parameterRoute') . 'preview')
	->text(Language::get('confirm')); ?>
