<h2 class="title_content">Dialog</h2>


<h3 class="title_content_sub">.js_confirm</h3>

<div>
	<a class="js_confirm field_button" href="<?php echo REWRITE_ROUTE; ?>preview">
		<span>
			<span><?php echo l('confirm'); ?></span>
		</span>
	</a>
</div>


<h3 class="title_content_sub">.title_dialog_default ~ .box_dialog_default</h3>

<div class="dialog dialog_default">
	<h3 class="title_dialog_default"><?php echo l('confirm'); ?></h3>
	<div class="box_dialog_default">
		<p><?php echo l('dialog_question') . l('question_mark'); ?></p>
		<a class="js_ok field_button">
			<span>
				<span><?php echo l('ok'); ?></span>
			</span>
		</a>
		<a class="js_cancel field_button">
			<span>
				<span><?php echo l('cancel'); ?></span>
			</span>
		</a>
	</div>
</div>

<?php if (LOGGED_IN == TOKEN): ?>
	<h3 class="title_content_sub">.title_dialog_admin ~ .box_dialog_admin</h3>

	<div class="dialog dialog_admin">
		<h3 class="title_dialog_admin"><?php echo l('confirm'); ?></h3>
		<div class="box_dialog_admin">
			<p><?php echo l('dialog_question') . l('question_mark'); ?></p>
			<a class="js_ok field_button_admin">
				<span>
					<span><?php echo l('ok'); ?></span>
				</span>
			</a>
			<a class="js_cancel field_button_admin">
				<span>
					<span><?php echo l('cancel'); ?></span>
				</span>
			</a>
		</div>
	</div>
<?php endif; ?>