<?php
namespace Redaxscript;

$suffix = $admin ? '-admin' : '';
$titlePartialElement = new Html\Element();
$titlePartialElement->init('h3', array(
	'class' => 'rs-title-preview-sub'
));
$textElement = new Html\Element();
$textElement
	->init('input', array(
		'class' => 'rs-field-default rs-field-text' . $suffix
	))
	->val(Language::get('preview', '_preview'));
$textareaElement = new Html\Element();
$textareaElement
	->init('textarea', array(
		'class' => 'rs-field-textarea' . $suffix
	))
	->val(Language::get('preview', '_preview'));
$optionNative = '<option>Placeholder text</option>';
$selectElement = new Html\Element();
$selectElement
	->init('select', array(
		'class' => 'rs-field-select' . $suffix
	))
	->html($optionNative . $optionNative . $optionNative);
?>

<!-- field text -->

<?php echo $titlePartialElement->text('.rs-field-text' . $suffix . ' + .rs-field-default'); ?>

<?php echo $textElement; ?>

<!-- disabled -->

<?php echo $titlePartialElement->text('.rs-field-text' . $suffix . '[disabled] + .rs-field-default'); ?>

<?php echo $textElement
	->copy()
	->attr('disabled', 'disabled'); ?>

<!-- field textarea -->

<?php echo $titlePartialElement->text('.rs-field-textarea' . $suffix); ?>

<?php echo $textareaElement; ?>

<!-- disabled -->

<?php echo $titlePartialElement->text('.rs-field-textarea' . $suffix . '[disabled]'); ?>

<?php echo $textareaElement
	->copy()
	->attr('disabled', 'disabled'); ?>

<!-- small -->

<?php echo $titlePartialElement->text('.rs-field-textarea' . $suffix . '.rs-field-small'); ?>

<?php echo $textareaElement
	->copy()
	->addClass('rs-field-small'); ?>

<!-- field select -->

<?php echo $titlePartialElement->text('.rs-field-select' . $suffix); ?>

<?php echo $selectElement; ?>

<!-- disabled -->

<?php echo $titlePartialElement->text('.rs-field-select' . $suffix . '[disabled]'); ?>

<?php echo $selectElement
	->copy()
	->attr('disabled', 'disabled'); ?>
