<h3 class="title_content_sub">.form_search > .field_search + .button_search</h3>

<?php search(); ?>


<h3 class="title_content_sub">.field_{type}</h3>

<?php echo form_element('form', '', 'js_validate_form form_default'); ?>
	<?php echo form_element('fieldset'); ?>
		<ul>
			<li><?php echo form_element('text', 'field_text', 'field_text', '', '', '.field_text'); ?></li>
			<li><?php echo select_element('field_select', 'field_select', '', array(
				l('select') => 'select',
				l('1', '_number') => 1,
				l('2', '_number') => 2,
				l('3', '_number') => 3
			), '', '.field_select'); ?></li>
			<li><?php echo select_element('field_select_multiple', 'field_select', '', array(
				l('1', '_number') => 1,
				l('2', '_number') => 2,
				l('3', '_number') => 3
			), '', '.field_select', 'multiple="multiple"'); ?></li>
			<li><?php echo form_element('textarea', 'field_textarea_field_small', 'field_textarea field_small', '', '', '.field_textarea + .field_small'); ?></li>
			<li><?php echo form_element('textarea', 'field_textarea', 'field_textarea', '', '', '.field_textarea[required]', 'required="required"'); ?></li>
		</ul>
	</fieldset>


	<h3 class="title_content_sub">.button_{type}</h3>

	<?php echo form_element('button', '', 'js_submit button_default', '', l('submit')); ?>
	<?php echo form_element('button', '', 'js_submit button_default button_large', '', l('submit')); ?>
	<?php echo form_element('button', '', 'js_submit button_default button_large', '', l('submit'), '', 'disabled="disabled"'); ?>
</form>
