<?php
namespace Redaxscript;

$titlePartialElement = new Html\Element();
$titlePartialElement->init('h3', array(
	'class' => 'rs-title-preview-sub'
));
$selectArray = array(
	1,
	2,
	3
);
$formElement = $admin ? new Admin\Html\Form(Registry::getInstance(), Language::getInstance()) : new Html\Form(Registry::getInstance(), Language::getInstance());
$formElement
	->init()
	->append('<fieldset><ul><li>')
	->label('text', array(
		'for' => $admin ? 'admin-text' : 'text'
	))
	->text(array(
		'id' => $admin ? 'admin-text' : 'text',
		'required' => 'required'
	))
	->append('</li><li>')
	->label('text[disabled]', array(
		'for' => $admin ? 'admin-text-disabled' : 'text-disabled'
	))
	->text(array(
		'disabled' => 'disabled',
		'id' => $admin ? 'admin-text-disabled' : 'text-disabled'
	))
	->append('</li><li>')
	->label('select', array(
		'for' => $admin ? 'admin-select' : 'select'
	))
	->select($selectArray, array(
		'id' => $admin ? 'admin-select' : 'select',
		'required' => 'required'
	))
	->append('</li><li>')
	->label('select[disabled]', array(
		'for' => $admin ? 'admin-select-disabled' : 'select-disabled'
	))
	->select($selectArray, array(
		'disabled' => 'disabled',
		'id' => $admin ? 'admin-select-disabled' : 'select-disabled'
	))
	->append('</li><li>')
	->label('textarea-small', array(
		'for' => $admin ? 'admin-textarea-small' : 'textarea-small'
	))
	->textarea(array(
		'class' => $admin ? 'rs-admin-field-textarea rs-admin-field-small' : 'rs-field-textarea rs-field-small',
		'id' => $admin ? 'admin-textarea-small' : 'textarea-small'
	))
	->append('</li><li>')
	->label('textarea-small[disabled]', array(
		'for' => $admin ? 'admin-textarea-small-disabled' : 'textarea-small-disabled'
	))
	->textarea(array(
		'class' => $admin ? 'rs-admin-field-textarea rs-admin-field-small' : 'rs-field-textarea rs-field-small',
		'disabled' => 'disabled',
		'id' => $admin ? 'admin-textarea-small-disabled' : 'textarea-small-disabled'
	))
	->append('</li><li>')
	->label('textarea', array(
		'for' => $admin ? 'admin-textarea' : 'textarea'
	))
	->textarea(array(
		'id' => $admin ? 'admin-textarea' : 'textarea',
		'required' => 'required'
	))
	->append('</li></ul></fieldset>')
	->submit()
	->reset();
?>

<!-- form -->

<?php echo $titlePartialElement->text($admin ? '.rs-admin-form-default' : '.rs-form-default'); ?>

<?php echo $formElement; ?>