<h2 class="title_content">Grid system</h2>


<h3 class="title_content_sub">.grid</h3>

<div class="clear_fix">
	<div class="grid s1o2">
		<div class="box_preview">s1o2</div>
	</div>
	<div class="grid s1o2">
		<div class="box_preview">s1o2</div>
	</div>
</div>

<div class="clear_fix">
	<div class="grid s1o3">
		<div class="box_preview">s1o3</div>
	</div>
	<div class="grid s2o3">
		<div class="box_preview">s2o3</div>
	</div>
</div>


<h3 class="title_content_sub">.grid_space</h3>

<div class="clear_fix">
	<div class="grid_space s1o2">
		<div class="box_preview">s1o2</div>
	</div>
	<div class="grid_space s1o2">
		<div class="box_preview">s1o2</div>
	</div>
</div>

<div class="clear_fix">
	<div class="grid_space s1o3">
		<div class="box_preview">s1o3</div>
	</div>
	<div class="grid_space s2o3">
		<div class="box_preview">s2o3</div>
	</div>
</div>


<h3 class="title_content_sub">.line > .grid</h3>

<div class="line clear_fix">
	<div class="grid s1o2">
		<div class="box_preview">s1o2</div>
	</div>
	<div class="grid s1o2">
		<div class="box_preview">s1o2</div>
	</div>
</div>

<div class="line clear_fix">
	<div class="grid s1o3">
		<div class="box_preview">s1o3</div>
	</div>
	<div class="grid s2o3">
		<div class="box_preview">s2o3</div>
	</div>
</div>


<h3 class="title_content_sub">.line > .grid_space</h3>

<div class="line clear_fix">
	<div class="grid_space s1o2">
		<div class="box_preview">s1o2</div>
	</div>
	<div class="grid_space s1o2">
		<div class="box_preview">s1o2</div>
	</div>
</div>

<div class="line clear_fix">
	<div class="grid_space s1o3">
		<div class="box_preview">s1o3</div>
	</div>
	<div class="grid_space s2o3">
		<div class="box_preview">s2o3</div>
	</div>
</div>


<h3 class="title_content_sub">.line_space > .grid_space</h3>

<div class="line_space clear_fix">
	<div class="grid_space s1o2">
		<div class="box_preview">s1o2</div>
	</div>
	<div class="grid_space s1o2">
		<div class="box_preview">s1o2</div>
	</div>
</div>

<div class="line_space clear_fix">
	<div class="grid_space s1o3">
		<div class="box_preview">s1o3</div>
	</div>
	<div class="grid_space s2o3">
		<div class="box_preview">s2o3</div>
	</div>
</div>


<h3 class="title_content_sub">.line_space > .grid > .grid_space</h3>

<div class="line_space clear_fix">
	<div class="grid s1o3">
		<div class="clear_fix">
			<div class="grid_space s1o3">
				<div class="box_preview">s1o3</div>
			</div>
			<div class="grid_space s2o3">
				<div class="box_preview">s2o3</div>
			</div>
		</div>
	</div>
	<div class="grid s2o3">
		<div class="grid_space s1o2">
			<div class="box_preview">s1o2</div>
		</div>
		<div class="grid_space s1o2">
			<div class="box_preview">s1o2</div>
		</div>
	</div>
</div>

<div class="line_space clear_fix">
	<div class="grid s1o3">
		<div class="clear_fix">
			<div class="grid_space s1o2">
				<div class="box_preview">s1o2</div>
			</div>
			<div class="grid_space s1o2">
				<div class="box_preview">s1o2</div>
			</div>
		</div>
	</div>
	<div class="grid s2o3">
		<div class="clear_fix">
			<div class="grid_space s1o3">
				<div class="box_preview">s1o3</div>
			</div>
			<div class="grid_space s1o3">
				<div class="box_preview">s1o3</div>
			</div>
			<div class="grid_space s1o3">
				<div class="box_preview">s1o3</div>
			</div>
		</div>
	</div>
</div>


<h2 class="title_content">Grid sizes</h2>

<div class="line clear_fix">
	<div class="grid_space s1o1">
		<div class="box_preview">s1o1</div>
	</div>
</div>

<?php for ($i = 2; $i < 9; $i++): ?>
	<div class="line clear_fix">
		<div class="grid_space s1o<?php echo $i; ?>">
			<div class="box_preview">s1o<?php echo $i; ?></div>
		</div>
		<div class="grid_space s<?php echo $i - 1; ?>o<?php echo $i; ?>">
			<div class="box_preview">s<?php echo $i - 1; ?>o<?php echo $i; ?></div>
		</div>
	</div>
<?php endfor; ?>

<div class="line clear_fix">
	<div class="grid_space gr1">
		<div class="box_preview">gr1</div>
	</div>
	<div class="grid_space gr2">
		<div class="box_preview">gr2</div>
	</div>
</div>