<?php
namespace Redaxscript;

$titlePartialElement = new Html\Element();
$titlePartialElement->init('h3',
[
	'class' => 'rs-title-preview-sub'
]);
$clearfixElement = new Html\Element();
$clearfixElement->init('div',
[
	'class' => 'rs-fn-clearfix'
]);
$gridElement = new Html\Element();
$gridElement->init('div');
$boxElement = new Html\Element();
$boxElement->init('div',
[
	'class' => 'rs-box-preview'
]);
$gridArray =
[
	[
		'.rs-fn-clearfix > .rs-fn-grid',
		'',
		'rs-fn-grid'
	],
	[
		'.rs-fn-clearfix > .rs-fn-grid-space',
		'',
		'rs-fn-grid-space'
	],
	[
		'.rs-fn-clearfix.line > .rs-fn-grid',
		'rs-line',
		'rs-fn-grid'
	],
	[
		'.rs-fn-clearfix.line > .rs-fn-grid-space',
		'rs-line',
		'rs-fn-grid-space'
	],
	[
		'.rs-fn-clearfix.rs-line-space > .rs-fn-grid',
		'rs-line-space',
		'rs-fn-grid'
	],
	[
		'.rs-fn-clearfix.rs-line-space > .rs-fn-grid-space',
		'rs-line-space',
		'rs-fn-grid-space'
	]
];
?>

<!-- grid combination -->

<?php foreach ($gridArray as $value): ?>

	<?php echo $titlePartialElement->text($value[0]); ?>

	<!-- s1o2 -->

	<?php echo $clearfixElement->addClass($value[1])->html(
		$gridElement->copy()->addClass($value[2] . ' rs-is-size1of2')->html($boxElement->text('s1o2')) .
		$gridElement->copy()->addClass($value[2] . ' rs-is-size1of2')->html($boxElement->text('s1o2'))
	); ?>

	<!-- s1o3 -->

	<?php echo $clearfixElement->addClass($value[1])->html(
		$gridElement->copy()->addClass($value[2] . ' rs-is-size1of3')->html($boxElement->text('s1o3')) .
		$gridElement->copy()->addClass($value[2] . ' rs-is-size2of3')->html($boxElement->text('s1o3'))
	); ?>

<?php endforeach; ?>

<!-- grid sizes -->

<?php echo $titlePartialElement->text('grid sizes'); ?>

<div class="rs-line rs-fn-clearfix">

	<?php echo $gridElement->copy()->addClass('rs-fn-grid-space rs-is-size1of1')->html($boxElement->text('s1o1')); ?>

</div>

<?php for ($i = 2; $i < 9; $i++): ?>

	<div class="rs-line rs-fn-clearfix">

		<?php echo $gridElement->copy()->addClass('rs-fn-grid-space rs-s1o' . $i)->html($boxElement->text('s1o' . $i)); ?>
		<?php echo $gridElement->copy()->addClass('rs-fn-grid-space rs-s' . ($i - 1) . 'o' . $i)->html($boxElement->text('s' . ($i - 1) . 'o' . $i)); ?>

	</div>

<?php endfor; ?>
