<h3 class="title_content_sub">.icon_flag</h3>

<?php
$languagesDirectory = new Redaxscript\Directory('languages');
$languagesDirectoryArray = $languagesDirectory->getArray();
?>

<div class="clearfix">
	<?php foreach ($languagesDirectoryArray as $language): ?><!--
		--><?php $language = substr($language, 0, 2); ?><!--
		--><span class="icon_flag language_<?php echo $language; ?>" title="<?php echo $language; ?>"><?php echo $language; ?></span><!--
	--><?php endforeach; ?>
</div>
