<?php
namespace Redaxscript;

$titlePartialElement = new Html\Element();
$titlePartialElement->init('h3', array(
	'class' => 'title_content_sub'
));
$iconElement = new Html\Element();
$iconElement->init('span', array(
	'class' => 'icon_flag'
));
$languagesDirectory = new Directory('languages');
$languagesDirectoryArray = $languagesDirectory->getArray();
?>

<!-- icon -->

<?php echo $titlePartialElement->text('.icon_flag.language_xx'); ?>

<div class="clearfix">

	<?php foreach ($languagesDirectoryArray as $value): ?>

		<?php $language = substr($value, 0, 2); ?>
		<?php echo $iconElement->copy()->addClass('language_' . $language)->text($language); ?>

	<?php endforeach; ?>

</div>
