<h2 class="title_content">
	<?php if (SECOND_PARAMETER !== 'icon'): ?>
		<a href="preview/icon" title="Icon">Icon</a>
	<?php else: ?>
		Icon
	<?php endif; ?>
</h2>


<h3 class="title_content_sub">.icon_flag</h3>

<?php
$languages_directory = new Redaxscript_Directory('languages');
$languages_directory_array = $languages_directory->get();
?>

<div class="clear_fix">
	<?php foreach ($languages_directory_array as $language): ?><!--
		--><?php $language = substr($language, 0, 2); ?><!--
		--><span class="icon_flag language_<?php echo $language; ?>" title="<?php echo $language; ?>"><?php echo $language; ?></span><!--
	--><?php endforeach; ?>
</div>
