<?php
namespace Redaxscript;

$titlePartialElement = new Html\Element();
$titlePartialElement->init('h3', array(
	'class' => 'rs-title-preview-sub'
));
$iconElement = new Html\Element();
$iconElement->init('span', array(
	'class' => 'rs-icon-flag'
));
$languagesDirectory = new Directory('languages');
$languagesDirectoryArray = $languagesDirectory->getArray();
?>

<!-- icon -->

<?php echo $titlePartialElement->text('.rs-icon-flag.rs-language-xx'); ?>

<div class="rs-clearfix">

	<?php foreach ($languagesDirectoryArray as $value): ?>

		<?php $language = substr($value, 0, 2); ?>
		<?php echo $iconElement->copy()->addClass('rs-language-' . $language)->text($language); ?>

	<?php endforeach; ?>

</div>
