<h2 class="title_content">Interface</h2>


<h3 class="title_content_sub">ul.list_default</h3>

<ul class="list_default">
	<li><?php echo l('1'); ?></li>
	<li><?php echo l('2'); ?>
		<ul>
			<li><?php echo l('1'); ?></li>
			<li><?php echo l('2'); ?></li>
			<li><?php echo l('3'); ?></li>
		</ul>
	</li>
	<li><?php echo l('3'); ?></li>
</ul>


<h3 class="title_content_sub">ol.list_default</h3>

<ol class="list_default">
	<li><?php echo l('1'); ?></li>
	<li><?php echo l('2'); ?>
		<ul>
			<li><?php echo l('1'); ?></li>
			<li><?php echo l('2'); ?></li>
			<li><?php echo l('3'); ?></li>
		</ul>
	</li>
	<li><?php echo l('3'); ?></li>
</ol>


<h3 class="title_content_sub">.list_search_result</h3>

<ol class="list_search_result">
	<li class="item_search_result">
		<a href="#" class="link_search_result" title="<?php echo l('preview_preview'); ?>"><?php echo l('preview_preview'); ?></a>
		<span class="date_search_result">01.01.2012</span>
	</li>
	<li class="item_search_result">
		<a href="#" class="link_search_result" title="<?php echo l('preview_preview'); ?>"><?php echo l('preview_preview'); ?></a>
		<span class="date_search_result">01.01.2012</span>
	</li>
</ol>


<h3 class="title_content_sub">.list_breadcrumb</h3>

<ul class="list_breadcrumb">
	<li><a href="#"><?php echo l('preview_preview'); ?></a></li>
	<li class="divider"><?php echo s('divider'); ?></li>
	<li><a href="#"><?php echo l('preview_preview'); ?></a></li>
	<li class="divider"><?php echo s('divider'); ?></li>
	<li><?php echo l('preview_preview'); ?></li>
</ul>


<h3 class="title_content_sub">.list_pagination</h3>

<?php echo pagination(1, 10, 'preview'); ?>

<?php echo pagination(5, 10, 'preview'); ?>

<?php echo pagination(10, 10, 'preview'); ?>


<h3 class="title_content_sub">.tooltip</h3>

<a class="link_default tooltip tooltip_default" data-tooltip="Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.">.tooltip_default</a>

<br />

<span class="tooltip tooltip_alternative" data-tooltip="Lorem ipsum dolor sit amet, consetetur sadipscing elitr.">.tooltip_alternative</span>
