<?php
namespace Redaxscript;

$titlePartialElement = new Html\Element();
$titlePartialElement->init('h3', array(
	'class' => 'rs-title-preview-sub'
));
$listOrderedElement = new Html\Element();
$listOrderedElement->init('ol', array(
	'class' => 'rs-list-default'
));
$listUnorderedElement = new Html\Element();
$listUnorderedElement->init('ul', array(
	'class' => 'rs-list-default'
));
$itemElement = new Html\Element();
$itemElement->init('li');
$listContent = '';
?>

<!-- list content -->

<?php for ($i = 0; $i < 5; $i++): ?>

	<?php $listContent .= $itemElement
		->copy()
		->text(Language::get($i + 1, '_number')); ?>

<?php endfor; ?>

<!-- list ordered -->

<?php echo $titlePartialElement->text('ol.rs-list-default'); ?>

<?php echo $listOrderedElement->html($listContent); ?>

<!-- list unordered -->

<?php echo $titlePartialElement->text('ul.rs-list-default'); ?>

<?php echo $listUnorderedElement->html($listContent); ?>
