<h2 class="title_content">Media</h2>


<h3 class="title_content_sub">.image + .image_default</h3>

<img class="image image_default" src="http://redaxscript.com/images/website/desktop/redaxscript_fully_responsive_admin.jpg" alt="default image" />


<h3 class="title_content_sub">.player + .player_default</h3>

<?php echo object_element('application/x-shockwave-flash', '', 'player player_default', '', 'player_default', '//youtube.com/v/FIA6F-XHCzk'); ?>