<?php
namespace Redaxscript;

$imageElement = new Html\Element();
$imageElement->init('img',
[
	'class' => 'rs-image-default',
	'src' => '//cdn.redaxscript.com/unsplash/817/1250x500.jpg'
]);
$videoElement = new Html\Element();
$videoElement->init('video',
[
	'autoplay' => 'true',
	'class' => 'rs-video-default',
	'src' => '//cdn.redaxscript.com/video/norway_1080.mp4'
]);
?>

<!-- image -->

<?php echo $imageElement; ?>

<!-- video -->

<?php echo $videoElement; ?>