<h2 class="title_content">
	<?php if (SECOND_PARAMETER !== 'media'): ?>
		<a href="preview/media" title="Media">Media</a>
	<?php else: ?>
		Media
	<?php endif; ?>
</h2>


<h3 class="title_content_sub">.image + .image_default</h3>

<img class="image image_default" src="//redaxscript.com/images/website/desktop/redaxscript_fully_responsive_admin.jpg" alt="default image" />


<h3 class="title_content_sub">object.player + .player_default</h3>

<?php echo object_element('application/x-shockwave-flash', '', 'player player_default', '', 'player_default', '//youtube.com/v/FIA6F-XHCzk'); ?>


<h3 class="title_content_sub">iframe.player + .player_default</h3>

<iframe src="//youtube.com/embed//FIA6F-XHCzk?vq=hd720" class="player player_default"></iframe>
