<?php
namespace Redaxscript;

$titlePartialElement = new Html\Element();
$titlePartialElement->init('h3',
[
	'class' => 'rs-title-preview-sub'
]);
$imageElement = new Html\Element();
$imageElement->init('img',
[
	'class' => 'rs-image rs-image-default'
]);
$playerElement = new Html\Element();
$playerElement->init('iframe',
[
	'class' => 'rs-video-default'
]);
?>

<!-- image -->

<?php echo $titlePartialElement->text('.rs-image-default'); ?>

<?php echo $imageElement->attr('src', '//i.imgur.com/SKpwO5M.jpg'); ?>

<!-- player -->

<?php echo $titlePartialElement->text('.rs-video-default'); ?>

<?php echo $playerElement->attr('src', '//youtube.com/embed//FIA6F-XHCzk?vq=hd720'); ?>
