<?php
namespace Redaxscript;

$imageElement = new Html\Element();
$imageElement->init('img',
[
	'class' => 'rs-image-default',
	'src' => '//cdn.redaxscript.com/unsplash/817/1250x500.jpg'
]);
$videoElement = new Html\Element();
$videoElement->init('video',
[
	'autoplay' => 'autoplay',
	'class' => 'rs-video-default',
	'muted' => 'muted',
	'src' => '//distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4'
]);
?>

<!-- image -->

<?php echo $imageElement; ?>

<!-- video -->

<?php echo $videoElement; ?>