<?php
namespace Redaxscript;

$registry = Registry::getInstance();
$language = Language::getInstance();
$linkElement = new Html\Element();
$linkElement
	->init('a',
	[
		'href' => $language->get('homepage', '_package')
	])
	->text('link');
$messenger = $admin ? new Admin\Messenger($registry) : new Messenger($registry);
$messenger->setRoute($language->get('preview', '_preview'), $admin ? 'preview#note-messenger-admin' : 'preview#note-messenger');
?>

<!--messenger -->

<?php echo $messenger->success('Success message with ' . $linkElement . ' element', 'Success'); ?>
<?php echo $messenger->warning('Warning message with ' . $linkElement . ' element', 'Warning'); ?>
<?php echo $messenger->error(
[
	'Error message with ' . $linkElement . ' element'
], 'Error'); ?>
<?php echo $messenger->info(
[
	'Info message with ' . $linkElement . ' element',
	'Info message with ' . $linkElement . ' element'
], 'Info'); ?>
