<?php
namespace Redaxscript;

$titlePartialElement = new Html\Element();
$titlePartialElement->init('h3',
[
	'class' => 'rs-title-preview-sub'
]);
$linkElement = new Html\Element();
$linkElement
	->init('a',
	[
		'href' => Language::get('homepage', '_package')
	])
	->text('link');
$boxElement = new Html\Element();
$boxElement->init('div',
[
	'class' => $admin ? 'rs-admin-box-note' : 'rs-box-note'
]);
$textElement = new Html\Element();
$textElement->init('input',
[
	'type' => 'text',
	'class' => $admin ? 'rs-admin-field-default rs-admin-field-text rs-admin-field-note' : 'rs-field-default rs-field-text rs-field-note',
	'placeholder' => 'Placeholder text'
]);
$optionNative = '<option>Placeholder text</option>';
$selectElement = new Html\Element();
$selectElement
	->init('select',
	[
		'class' => $admin ? 'rs-admin-field-select rs-admin-field-note' : 'rs-field-select rs-field-note',
	])
	->html($optionNative . $optionNative . $optionNative);
$noteArray =
[
	$admin ? 'rs-admin-is-error' : 'rs-is-error',
	$admin ? 'rs-admin-is-warning' : 'rs-is-warning',
	$admin ? 'rs-admin-is-success' : 'rs-is-success',
	$admin ? 'rs-admin-is-info' : 'rs-is-info'
];
$registry = Registry::getInstance();
$messenger = $admin ? new Admin\Messenger($registry) : new Messenger($registry);
$messenger->setRoute(Language::get('preview', '_preview'), 'preview#note');
?>

<!--messenger -->

<?php echo $titlePartialElement->text($admin ? '.rs-admin-title-note.rs-admin-is-success + .rs-admin-box-note.rs-admin-is-success' : '.rs-title-note.rs-is-success + .rs-box-note.rs-is-success'); ?>
<?php echo $messenger->success('Plain success message with ' . $linkElement . ' element', 'Success'); ?>

<?php echo $titlePartialElement->text($admin ? '.rs-admin-title-note.rs-admin-is-warning + .rs-admin-box-note.rs-admin-is-warning' : '.rs-title-note.rs-is-warning + .rs-box-note.rs-is-warning'); ?>
<?php echo $messenger->warning('Plain warning message with ' . $linkElement . ' element', 'Warning'); ?>

<?php echo $titlePartialElement->text($admin ? '.rs-admin-title-note.rs-admin-is-error + .rs-admin-box-note.rs-admin-is-error' : '.rs-title-note.rs-is-error + .rs-box-note.rs-is-error'); ?>
<?php echo $messenger->error('Plain error message with ' . $linkElement . ' element', 'Error'); ?>

<?php echo $titlePartialElement->text($admin ? '.rs-admin-title-note.rs-admin-is-info + .rs-admin-box-note.rs-admin-is-info' : '.rs-title-note.rs-is-info + .rs-box-note.rs-is-info'); ?>
<?php echo $messenger->info('Plain info message with ' . $linkElement . ' element', 'Info'); ?>

<!-- text field -->

<form>

	<?php foreach ($noteArray as $value): ?>

		<?php echo $titlePartialElement->text($admin ? '.rs-admin-field-note.' : '.rs-field-note.')->append($value); ?>
		<?php echo $textElement->copy()->addClass($value)->val($value); ?>

	<?php endforeach; ?>

</form>

<!-- select field -->

<form>

	<?php foreach ($noteArray as $value): ?>

		<?php echo $titlePartialElement->text($admin ? '.rs-admin-field-note.' : '.rs-field-note.')->append($value); ?>
		<?php echo $selectElement->copy()->addClass($value)->val($value); ?>

	<?php endforeach; ?>

</form>
