<?php
namespace Redaxscript;

$registry = Registry::getInstance();
$language = Language::getInstance();
$linkElement = new Html\Element();
$linkElement
	->init('a',
	[
		'href' => $language->get('_package')['homepage']
	])
	->text('link');
$messenger = $admin ? new Admin\View\Helper\Messenger($registry) : new View\Helper\Messenger($registry);
$messenger->setRoute($language->get('_preview')['preview'], $admin ? 'module/preview#note-messenger-admin' : 'module/preview#note-messenger');
?>

<!--messenger -->

<?php echo $messenger->success('Success message with ' . $linkElement . ' element', 'Success'); ?>
<?php echo $messenger->info(
[
	'Info message with ' . $linkElement . ' element',
	'Info message with ' . $linkElement . ' element'
], 'Info'); ?>
<?php echo $messenger->warning('Warning message with ' . $linkElement . ' element', 'Warning'); ?>
<?php echo $messenger->error(
[
	'Error message with ' . $linkElement . ' element'
], 'Error'); ?>