<h3 class="title_content_sub">.box_note</h3>

<div class="box_note note_error">.note_error <a href="#">link</a></div>
<div class="box_note note_warning">.note_warning <a href="#">link</a></div>
<div class="box_note note_success">.note_success <a href="#">link</a></div>
<div class="box_note note_info">.note_info <a href="#">link</a></div>

<?php echo form_element('form'); ?>


	<h3 class="title_content_sub">input.field_note</h3>

	<?php echo form_element('fieldset'); ?>
		<ul>
			<li><?php echo form_element('text', '', 'field_text field_note note_error', '', '.note_error'); ?></li>
			<li><?php echo form_element('text', '', 'field_text field_note note_warning', '', '.note_warning'); ?></li>
			<li><?php echo form_element('text', '', 'field_text field_note note_success', '', '.note_success'); ?></li>
			<li><?php echo form_element('text', '', 'field_text field_note note_info', '', '.note_info'); ?></li>
		</ul>
	</fieldset>


	<h3 class="title_content_sub">select.field_note</h3>

	<?php echo form_element('fieldset'); ?>
		<ul>
			<li><?php echo select_element('', 'field_select field_note note_error', '', array(
				l('select') => 'select',
				l('1', '_number') => 1,
				l('2', '_number') => 2,
				l('3', '_number') => 3
			)); ?></li>
			<li><?php echo select_element('', 'field_select field_note note_warning', '', array(
				l('select') => 'select',
				l('1', '_number') => 1,
				l('2', '_number') => 2,
				l('3', '_number') => 3
			)); ?></li>
			<li><?php echo select_element('', 'field_select field_note note_success', '', array(
				l('select') => 'select',
				l('1', '_number') => 1,
				l('2', '_number') => 2,
				l('3', '_number') => 3
			)); ?></li>
			<li><?php echo select_element('', 'field_select field_note note_info', '', array(
				l('select') => 'select',
				l('1', '_number') => 1,
				l('2', '_number') => 2,
				l('3', '_number') => 3
			)); ?></li>
		</ul>
	</fieldset>
</form>
