<?php
namespace Redaxscript;

$titlePartialElement = new Html\Element();
$titlePartialElement->init('h3', array(
	'class' => 'rs-title-preview-sub'
));
$linkElement = new Html\Element();
$linkElement
	->init('a', array(
		'href' => '#'
	))
	->text('link');
$boxElement = new Html\Element();
$boxElement->init('div', array(
	'class' => 'rs-box-note'
));
$fieldTextElement = new Html\Element();
$fieldTextElement->init('input', array(
	'type' => 'text',
	'class' => 'rs-field-text rs-field-note',
	'placeholder' => 'Placeholder text'
));
$optionNative = '<option>Placeholder text</option>';
$fieldSelectElement = new Html\Element();
$fieldSelectElement
	->init('select', array(
		'class' => 'rs-field-select rs-field-note',
	))
	->html($optionNative . $optionNative . $optionNative);
$noteArray = array(
	'rs-note-error',
	'rs-note-warning',
	'rs-note-success',
	'rs-note-info'
);
?>

<!-- several boxes -->

<?php foreach ($noteArray as $value): ?>

	<?php echo $titlePartialElement->text('.rs-box-note.' . $value); ?>
	<?php echo $boxElement->copy()->addClass($value)->html('Placeholder text and ' . $linkElement . '.'); ?>

<?php endforeach; ?>

<!-- text fields -->

<form>

	<?php foreach ($noteArray as $value): ?>

		<?php echo $titlePartialElement->text('.rs-field-note.' . $value); ?>
		<?php echo $fieldTextElement->copy()->addClass($value)->val($value); ?>

	<?php endforeach; ?>

</form>

<!-- select fields -->

<form>

	<?php foreach ($noteArray as $value): ?>

		<?php echo $titlePartialElement->text('.rs-field-note.' . $value); ?>
		<?php echo $fieldSelectElement->copy()->addClass($value)->val($value); ?>

	<?php endforeach; ?>

</form>
