<?php
namespace Redaxscript;

$pagination = new View\Helper\Pagination(Registry::getInstance(), Language::getInstance());
$pagination->init();
?>

<!-- pagination -->

<?php echo $pagination->render('module/preview#pagination', 5000, 10000); ?>
<?php echo $pagination->render('module/preview#pagination', 5000, 10000, 1); ?>

<?php for ($i = 1; $i < 11; $i++): ?>
	<?php echo $pagination->render('module/preview#pagination', $i, 10, 2); ?>
<?php endfor; ?>