<?php
namespace Redaxscript;

$registry = Registry::getInstance();
$language = Language::getInstance();
$listElement = new Html\Element();
$listElement->init('ul',
[
	'class' => $admin ? 'rs-admin-js-list-tab rs-admin-list-tab' : 'rs-js-list-tab rs-list-tab'
]);
$boxElement = new Html\Element();
$boxElement->init('div',
[
	'class' => $admin ? 'rs-admin-js-box-tab rs-admin-box-tab' : 'rs-js-box-tab rs-box-tab'
]);
$itemElement = new Html\Element();
$itemElement->init('li');
$linkElement = new Html\Element();
$linkElement->init('a');
$setElement = new Html\Element();
$setElement->init('div',
[
	'class' => $admin ? 'rs-admin-js-set-tab rs-admin-set-tab' : 'rs-js-set-tab rs-set-tab'
]);
$outputItem = null;
$outputBox = null;
?>

<!-- tab -->

<div class="<?php echo $admin ? 'rs-admin-js-tab rs-admin-component-tab' : 'rs-js-tab rs-component-tab'; ?>">

	<?php for ($i = 1; $i < 6; $i++): ?>

		<?php $id = uniqid('tab-') . $i; ?>

		<?php $outputItem .= $itemElement
				->copy()
				->addClass($i === 2 ? $admin ? 'rs-admin-js-item-active rs-admin-item-active' : 'rs-js-item-active rs-item-active' : null)
				->html(
					$linkElement
						->attr('href', $registry->get('parameterRoute') . $registry->get('fullRoute') . '#' . $id)
						->text($language->get($i, '_number'))
				); ?>

		<?php $outputBox .= $setElement
				->copy()
				->addClass($i === 2 ? $admin ? 'rs-admin-js-set-active rs-admin-set-active' : 'rs-js-set-active rs-set-active' : null)
				->attr('id', $id)
				->text($language->get($i, '_number')); ?>

	<?php endfor; ?>

	<?php echo $listElement->copy()->html($outputItem); ?>
	<?php echo $boxElement->copy()->html($outputBox); ?>

</div>