<?php
namespace Redaxscript;

$suffix = isset($admin) ? '-admin' : '-default';
$titlePartialElement = new Html\Element();
$titlePartialElement->init('h3', array(
	'class' => 'rs-title-preview-sub'
));
$listTabElement = new Html\Element();
$listTabElement->init('ul', array(
	'class' => 'rs-js-list-tab rs-list-tab rs-list-tab' . $suffix
));
$boxTabElement = new Html\Element();
$boxTabElement->init('div', array(
	'class' => 'rs-js-box-tab rs-box-tab rs-box-tab' . $suffix
));
$itemTabElement = new Html\Element();
$itemTabElement->init('li');
$setTabElement = new Html\Element();
$setTabElement->init('div', array(
	'class' => 'rs-js-set-tab rs-set-tab rs-set-tab' . $suffix
));
$listContent = '';
$boxContent = '';
$itemActive = 'rs-js-item-active rs-item-active';
$setActive = 'rs-js-set-active rs-set-active';
$itemArray = array(
	'rs-item-first',
	'rs-item-second',
	'rs-item-third',
	'rs-item-fourth',
	'rs-item-last'
);
?>

<!-- list and set content -->

<?php foreach ($itemArray as $key => $value): ?>

	<?php $id = 'tab' . $suffix . '-' . $key; ?>

	<?php $listContent .= $itemTabElement
		->copy()
		->addClass($key === 0 ? $itemActive : '')
		->addClass($value)
		->html('<a href="' . Registry::get('rewriteRoute') . Registry::get('fullRoute') . '#' . $id . '">' . Language::get($key + 1, '_number') . '</a>'); ?>

	<?php $boxContent .= $setTabElement
			->copy()
			->addClass($key === 0 ? $setActive : '')
			->attr('id', $id)
			->text(Language::get($key + 1, '_number')); ?>

<?php endforeach; ?>

<!-- tab -->

<?php echo $titlePartialElement->text('.rs-list-accordion' . $suffix . ' + .rs-box-tab' . $suffix); ?>

<div class="rs-js-tab rs-tab">

	<?php echo $listTabElement->copy()->html($listContent); ?>
	<?php echo $boxTabElement->copy()->html($boxContent); ?>

</div>
