<?php if (LOGGED_IN == TOKEN): ?>
	<h2 class="title_content">
		<?php if (SECOND_PARAMETER !== 'tab_admin'): ?>
			<a href="preview/tab_admin" title="Tab Admin">Tab Admin</a>
		<?php else: ?>
			Tab Admin
		<?php endif; ?>
	</h2>

	<h3 class="title_content_sub">.js_tab (div > ul + div > div)</h3>

	<div class="js_tab">
		<ul class="js_list_tab list_tab list_tab_admin">
			<li class="js_item_active item_first item_active">
				<a href="<?php echo REWRITE_ROUTE . FULL_ROUTE; ?>#tab-admin-1" title="<?php echo l('1', 'number'); ?>"><?php echo l('1', 'number'); ?></a>
			</li>
			<li class="item_second">
				<a href="<?php echo REWRITE_ROUTE . FULL_ROUTE; ?>#tab-admin-2" title="<?php echo l('2', 'number'); ?>"><?php echo l('2', 'number'); ?></a>
			</li>
			<li class="item_last">
				<a href="<?php echo REWRITE_ROUTE . FULL_ROUTE; ?>#tab-admin-3" title="<?php echo l('3', 'number'); ?>"><?php echo l('3', 'number'); ?></a>
			</li>
		</ul>

		<div class="js_box_tab box_tab box_tab_admin">
			<div id="tab-admin-1" class="js_set_tab js_set_active set_tab set_tab_admin set_active">
				<?php echo l('1', '_number'); ?>
			</div>
			<div id="tab-admin-2" class="js_set_tab set_tab set_tab_admin">
				<?php echo l('2', '_number'); ?>
			</div>
			<div id="tab-admin-3" class="js_set_tab set_tab set_tab_admin">
				<?php echo l('3', '_number'); ?>
			</div>
		</div>
	</div>


	<h3 class="title_content_sub">.js_tab (form > ul + div > fieldset)</h3>

	<form class="js_tab">
		<ul class="js_list_tab list_tab list_tab_admin">
			<li class="item_first">
				<a href="<?php echo REWRITE_ROUTE . FULL_ROUTE; ?>#tab-admin-4" title="<?php echo l('4', 'number'); ?>"><?php echo l('4', 'number'); ?></a>
			</li>
			<li class="js_item_active item_second item_active">
				<a href="<?php echo REWRITE_ROUTE . FULL_ROUTE; ?>#tab-admin-5" title="<?php echo l('5', 'number'); ?>"><?php echo l('5', 'number'); ?></a>
			</li>
			<li class="item_last">
				<a href="<?php echo REWRITE_ROUTE . FULL_ROUTE; ?>#tab-admin-6" title="<?php echo l('6', 'number'); ?>"><?php echo l('6', 'number'); ?></a>
			</li>
		</ul>

		<div class="js_box_tab box_tab box_tab_admin">
			<fieldset id="tab-admin-4" class="js_set_tab set_tab set_tab_admin">
				<ul>
					<li>
						<?php echo l('4', '_number'); ?>
					</li>
				</ul>
			</fieldset>
			<fieldset id="tab-admin-5" class="js_set_tab js_set_active set_tab set_tab_admin set_active">
				<ul>
					<li>
						<?php echo l('5', '_number'); ?>
					</li>
				</ul>
			</fieldset>
			<fieldset id="tab-admin-6" class="js_set_tab set_tab set_tab_admin">
				<ul>
					<li>
						<?php echo l('6', '_number'); ?>
					</li>
				</ul>
			</fieldset>
		</div>
	</form>
<?php endif; ?>
