<?php
namespace Redaxscript;

$suffix = isset($admin) ? '_admin' : '_default';
$titlePartialElement = new Element('h3', array(
	'class' => 'title_content_sub'
));
$tableElement = new Element('table', array(
	'class' => 'table table' . $suffix
));
$theadElement = new Element('thead');
$tfootElement = new Element('tfoot');
$tbodyElement = new Element('tbody');
$captionElement = new Element('caption');
$thElement = new Element('th');
$tdElement = new Element('td');
$theadContent = '';
$tfootContent = '';
$tbodyContent = '';
$columnArray = array(
	'column_first',
	'column_second',
	'column_third',
	'column_fourth',
	'column_last'
);
?>

<!-- thead and tfoot content -->

<?php for ($i = 0; $i < 5; $i++): ?>

	<?php $theadContent .= $thElement
		->copy()
		->addClass('s1o5 ' . $columnArray[$i])
		->text(Language::get($i + 1, '_number')); ?>

	<?php $tfootContent .= $tdElement
		->copy()
		->addClass($columnArray[$i])
		->text(Language::get($i + 1, '_number')); ?>

<?php endfor; ?>

<!-- tbody content -->

<?php foreach ($columnArray as $value): ?>

	<?php $tbodyContent .= $tdElement
		->copy()
		->addClass($value)
		->text(Language::get('preview', '_preview')); ?>

<?php endforeach; ?>

<!-- table -->

<?php echo $titlePartialElement->text('.table.table' . $suffix); ?>

<div class="wrapper_table<?php echo $suffix; ?>">

	<?php echo $tableElement->html(
		$theadElement->html($theadContent) .
		$tfootElement->html($tfootContent) .
		$tbodyElement->html(
			'<tr>' . $tbodyContent . '</tr>' .
			'<tr>' . $tbodyContent . '</tr>' .
			'<tr>' . $tbodyContent . '</tr>'
		)
	); ?>

</div>

<!-- table with caption -->

<?php echo $titlePartialElement->text('.table.table' . $suffix); ?>

<div class="wrapper_table<?php echo $suffix; ?>">

	<?php echo $tableElement->html(
		$captionElement->text('Caption') .
		$tbodyElement->html(
			'<tr>' . $tbodyContent . '</tr>' .
			'<tr>' . $tbodyContent . '</tr>' .
			'<tr>' . $tbodyContent . '</tr>'
		)
	); ?>

</div>