<?php
namespace Redaxscript;

$tableElement = new Html\Element();
$tableElement->init('table',
[
	'class' => $admin ? 'rs-admin-table-default' : 'rs-table-default'
]);
$theadElement = new Html\Element();
$theadElement->init('thead');
$tfootElement = new Html\Element();
$tfootElement->init('tfoot');
$tbodyElement = new Html\Element();
$tbodyElement->init('tbody');
$captionElement = new Html\Element();
$captionElement->init('caption');
$thElement = new Html\Element();
$thElement->init('th');
$tdElement = new Html\Element();
$tdElement->init('td');
$outputHead = null;
$outputFoot = null;
$outputBody = null;
?>

<!-- content -->

<?php for ($i = 1; $i < 6; $i++): ?>

	<?php $outputHead .= $thElement
		->copy()
		->addClass($admin ? 'rs-admin-is-size-1of5' : 'rs-is-size1of5')
		->text(Language::get($i, '_number')); ?>

	<?php $outputFoot .= $tdElement
		->text(Language::get($i, '_number')); ?>

	<?php $outputBody .= $tdElement
		->text(Language::get('preview', '_preview')); ?>

<?php endfor; ?>

<!-- table -->

<div class="<?php echo $admin ? 'rs-admin-wrapper-table' : 'rs-wrapper-table'; ?>">

	<?php echo $tableElement->html(
		$theadElement->html('<tr>' . $outputHead . '</tr>') .
		$tfootElement->html('<tr>' . $outputFoot . '</tr>') .
		$tbodyElement->html(
			'<tr>' . $outputBody . '</tr>' .
			'<tr>' . $outputBody . '</tr>' .
			'<tr>' . $outputBody . '</tr>'
		)
	); ?>

</div>

<!-- table with caption -->

<div class="<?php echo $admin ? 'rs-admin-wrapper-table' : 'rs-wrapper-table'; ?>">

	<?php echo $tableElement->html(
		$captionElement->text('Caption') .
		$tbodyElement->html(
			'<tr>' . $outputBody . '</tr>' .
			'<tr>' . $outputBody . '</tr>' .
			'<tr>' . $outputBody . '</tr>'
		)
	); ?>

</div>
