<h2 class="title_content">
	<?php if (SECOND_PARAMETER !== 'table'): ?>
		<a href="preview/table" title="Table">Table</a>
	<?php else: ?>
		Table
	<?php endif; ?>
</h2>


<h3 class="title_content_sub">.table + .table_default</h3>

<div class="wrapper_table_default">
	<table class="table table_default">
		<thead>
			<tr>
				<th class="s1o5 column_first"><?php echo l('1', '_number'); ?></th>
				<th class="s1o5 column_second"><?php echo l('2', '_number'); ?></th>
				<th class="s1o5 column_third"><?php echo l('3', '_number'); ?></th>
				<th class="s1o5 column_fourth"><?php echo l('4', '_number'); ?></th>
				<th class="s1o5 column_last"><?php echo l('5', '_number'); ?></th>
			</tr>
		</thead>
		<tfoot>
			<tr>
				<td class="column_first"><?php echo l('1', '_number'); ?></td>
				<td class="column_second"><?php echo l('2', '_number'); ?></td>
				<td class="column_third"><?php echo l('3', '_number'); ?></td>
				<td class="column_fourth"><?php echo l('4', '_number'); ?></td>
				<td class="column_last"><?php echo l('5', '_number'); ?></td>
			</tr>
		</tfoot>
		<tbody>
			<tr>
				<td class="column_first"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_second"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_third"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_fourth"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_last"><?php echo l('preview', 'preview'); ?></td>
			</tr>
			<tr>
				<td class="column_first"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_second"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_third"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_fourth"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_last"><?php echo l('preview', 'preview'); ?></td>
			</tr>
			<tr>
				<td class="column_first"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_second"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_third"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_fourth"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_last"><?php echo l('preview', 'preview'); ?></td>
			</tr>
		</tbody>
	</table>
</div>


<h3 class="title_content_sub">.table + .table_default</h3>

<div class="wrapper_table_default">
	<table class="table table_default">
		<caption>Caption</caption>
		<tbody>
			<tr>
				<td class="column_first"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_second"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_third"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_fourth"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_last"><?php echo l('preview', 'preview'); ?></td>
			</tr>
			<tr>
				<td class="column_first"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_second"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_third"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_fourth"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_last"><?php echo l('preview', 'preview'); ?></td>
			</tr>
			<tr>
				<td class="column_first"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_second"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_third"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_fourth"><?php echo l('preview', 'preview'); ?></td>
				<td class="column_last"><?php echo l('preview', 'preview'); ?></td>
			</tr>
		</tbody>
	</table>
</div>
