<?php if (LOGGED_IN == TOKEN): ?>
	<h2 class="title_content">
		<?php if (SECOND_PARAMETER !== 'table_admin'): ?>
			<a href="preview/table_admin" title="Table Admin">Table Admin</a>
		<?php else: ?>
			Table Admin
		<?php endif; ?>
	</h2>


	<h3 class="title_content_sub">.table + .table_admin</h3>

	<div class="wrapper_table_admin">
		<table class="table table_admin">
			<thead>
			<tr>
				<th class="s1o4 column_first"><?php echo l('1'); ?></th>
				<th class="s1o4 column_second"><?php echo l('2'); ?></th>
				<th class="s1o4 column_third"><?php echo l('3'); ?></th>
				<th class="s1o4 column_fourth"><?php echo l('4'); ?></th>
				<th class="column_move column_last"><?php echo l('rank'); ?></th>
			</tr>
			</thead>
			<tfoot>
			<tr>
				<td class="column_first"><?php echo l('1'); ?></td>
				<td class="column_second"><?php echo l('2'); ?></td>
				<td class="column_third"><?php echo l('3'); ?></td>
				<td class="column_fourth"><?php echo l('4'); ?></td>
				<td class="column_move column_last"><?php echo l('rank'); ?></td>
			</tr>
			</tfoot>
			<tbody>
			<tr>
				<td class="column_first"><?php echo l('preview_preview'); ?></td>
				<td class="column_second"><?php echo l('preview_preview'); ?></td>
				<td class="column_third"><?php echo l('preview_preview'); ?></td>
				<td class="column_fourth"><?php echo l('preview_preview'); ?></td>
				<td class="column_move column_last">
					<span class="move_up"><?php echo l('up'); ?></span>
					<span class="move_down"><?php echo l('down'); ?></span>
				</td>
			</tr>
			<tr>
				<td class="column_first"><?php echo l('preview_preview'); ?></td>
				<td class="column_second"><?php echo l('preview_preview'); ?></td>
				<td class="column_third"><?php echo l('preview_preview'); ?></td>
				<td class="column_fourth"><?php echo l('preview_preview'); ?></td>
				<td class="column_move column_last">
					<span class="move_up"><?php echo l('up'); ?></span>
					<span class="move_down"><?php echo l('down'); ?></span>
				</td>
			</tr>
			<tr>
				<td class="column_first"><?php echo l('preview_preview'); ?></td>
				<td class="column_second"><?php echo l('preview_preview'); ?></td>
				<td class="column_third"><?php echo l('preview_preview'); ?></td>
				<td class="column_fourth"><?php echo l('preview_preview'); ?></td>
				<td class="column_move column_last">
					<span class="move_up"><?php echo l('up'); ?></span>
					<span class="move_down"><?php echo l('down'); ?></span>
				</td>
			</tr>
			</tbody>
		</table>
	</div>

	<h3 class="title_content_sub">.table + .table_admin</h3>

	<div class="wrapper_table_admin">
		<table class="table table_admin">
			<caption>Caption</caption>
			<tbody>
			<tr>
				<td class="column_first"><?php echo l('preview_preview'); ?></td>
				<td class="column_second"><?php echo l('preview_preview'); ?></td>
				<td class="column_third"><?php echo l('preview_preview'); ?></td>
				<td class="column_fourth"><?php echo l('preview_preview'); ?></td>
				<td class="column_move column_last">
					<span class="move_up"><?php echo l('up'); ?></span>
					<span class="move_down"><?php echo l('down'); ?></span>
				</td>
			</tr>
			<tr>
				<td class="column_first"><?php echo l('preview_preview'); ?></td>
				<td class="column_second"><?php echo l('preview_preview'); ?></td>
				<td class="column_third"><?php echo l('preview_preview'); ?></td>
				<td class="column_fourth"><?php echo l('preview_preview'); ?></td>
				<td class="column_move column_last">
					<span class="move_up"><?php echo l('up'); ?></span>
					<span class="move_down"><?php echo l('down'); ?></span>
				</td>
			</tr>
			<tr>
				<td class="column_first"><?php echo l('preview_preview'); ?></td>
				<td class="column_second"><?php echo l('preview_preview'); ?></td>
				<td class="column_third"><?php echo l('preview_preview'); ?></td>
				<td class="column_fourth"><?php echo l('preview_preview'); ?></td>
				<td class="column_move column_last">
					<span class="move_up"><?php echo l('up'); ?></span>
					<span class="move_down"><?php echo l('down'); ?></span>
				</td>
			</tr>
			</tbody>
		</table>
	</div>
<?php endif; ?>
