<?php
namespace Redaxscript;

$suffix = $admin ? '-admin' : '-default';
$titlePartialElement = new Html\Element();
$titlePartialElement->init('h3', array(
	'class' => 'rs-title-preview-sub'
));
$tableElement = new Html\Element();
$tableElement->init('table', array(
	'class' => 'rs-table rs-table' . $suffix
));
$theadElement = new Html\Element();
$theadElement->init('thead');
$tfootElement = new Html\Element();
$tfootElement->init('tfoot');
$tbodyElement = new Html\Element();
$tbodyElement->init('tbody');
$captionElement = new Html\Element();
$captionElement->init('caption');
$thElement = new Html\Element();
$thElement->init('th');
$tdElement = new Html\Element();
$tdElement->init('td');
$theadContent = '';
$tfootContent = '';
$tbodyContent = '';
$columnArray = array(
	'rs-column-first',
	'rs-column-second',
	'rs-column-third',
	'rs-column-fourth',
	'rs-column-last'
);
?>

<!-- thead and tfoot content -->

<?php for ($i = 0; $i < 5; $i++): ?>

	<?php $theadContent .= $thElement
		->copy()
		->addClass('rs-s1o5 ' . $columnArray[$i])
		->text(Language::get($i + 1, '_number')); ?>

	<?php $tfootContent .= $tdElement
		->copy()
		->addClass($columnArray[$i])
		->text(Language::get($i + 1, '_number')); ?>

<?php endfor; ?>

<!-- tbody content -->

<?php foreach ($columnArray as $value): ?>

	<?php $tbodyContent .= $tdElement
		->copy()
		->addClass($value)
		->text(Language::get('preview', '_preview')); ?>

<?php endforeach; ?>

<!-- table -->

<?php echo $titlePartialElement->text('.rs-table.rs-table' . $suffix); ?>

<div class="rs-wrapper-table<?php echo $suffix; ?>">

	<?php echo $tableElement->html(
		$theadElement->html($theadContent) .
		$tfootElement->html($tfootContent) .
		$tbodyElement->html(
			'<tr>' . $tbodyContent . '</tr>' .
			'<tr>' . $tbodyContent . '</tr>' .
			'<tr>' . $tbodyContent . '</tr>'
		)
	); ?>

</div>

<!-- table with caption -->

<?php echo $titlePartialElement->text('.rs-table.rs-table' . $suffix); ?>

<div class="rs-wrapper-table<?php echo $suffix; ?>">

	<?php echo $tableElement->html(
		$captionElement->text('Caption') .
		$tbodyElement->html(
			'<tr>' . $tbodyContent . '</tr>' .
			'<tr>' . $tbodyContent . '</tr>' .
			'<tr>' . $tbodyContent . '</tr>'
		)
	); ?>

</div>
