<?php
namespace Redaxscript;

$titlePartialElement = new Html\Element('h3', array(
	'class' => 'title_content_sub'
));
?>

<!-- tooltip default -->

<?php echo $titlePartialElement->text('.link_default.tooltip.tooltip_default'); ?>

<a class="link_default tooltip tooltip_default" data-tooltip="Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua."><?php echo Language::get('preview', '_preview'); ?></a>

<!-- tooltip alternative -->

<?php echo $titlePartialElement->text('.tooltip.tooltip_alternative'); ?>

<span class="tooltip tooltip_alternative" data-tooltip="Lorem ipsum dolor sit amet, consetetur sadipscing elitr."><?php echo Language::get('preview', '_preview'); ?></span>
