<?php
namespace Redaxscript;

$titlePartialElement = new Html\Element();
$titlePartialElement->init('h3', array(
	'class' => 'rs-title-preview-sub'
));
?>

<!-- tooltip default -->

<?php echo $titlePartialElement->text('.rs-link-default.rs-has-tooltip.rs-tooltip-default'); ?>

<a class="rs-link-default rs-has-tooltip rs-tooltip-default" data-tooltip="Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua."><?php echo Language::get('preview', '_preview'); ?></a>

<!-- tooltip alternative -->

<?php echo $titlePartialElement->text('.rs-has-tooltip.rs-tooltip-alternative'); ?>

<span class="rs-has-tooltip rs-tooltip-alternative" data-tooltip="Lorem ipsum dolor sit amet, consetetur sadipscing elitr."><?php echo Language::get('preview', '_preview'); ?></span>
