<h2 class="title_content">
	<?php if (SECOND_PARAMETER !== 'typography'): ?>
		<a href="preview/typography" title="Typography">Typography</a>
	<?php else: ?>
		Typography
	<?php endif; ?>
</h2>


<h3 class="title_content_sub">.link_default</h3>

<a href="#" class="link_default" title="link_default"><?php echo l('preview_preview'); ?></a>


<h3 class="title_content_sub">.link_read_more</h3>

<a href="#" class="link_read_more" title="link_read_more"><?php echo l('preview_preview'); ?></a>


<h3 class="title_content_sub">.title_content</h3>

<h3 class="title_content"><?php echo l('preview_preview'); ?></h3>


<h3 class="title_content_sub">.title_content_sub</h3>

<h3 class="title_content_sub"><?php echo l('preview_preview'); ?></h3>


<h3 class="title_content_sub">.title_comment</h3>

<h3 class="title_comment"><?php echo l('preview_preview'); ?></h3>


<h3 class="title_content_sub">.title_extra</h3>

<h3 class="title_extra"><?php echo l('preview_preview'); ?></h3>
