<?php
namespace Redaxscript;

$titlePartialElement = new Html\Element();
$titlePartialElement->init('h3', array(
	'class' => 'rs-title-preview-sub'
));
$linkElement = new Html\Element();
$linkElement
	->init('a', array(
		'href' => Language::get('homepage', '_package')
	))
	->text(Language::get('preview', '_preview'));
$paragraphElement = new Html\Element();
$paragraphElement
	->init('p')
	->text(Language::get('preview', '_preview'));
$titleElement = new Html\Element();
$titleElement
	->init('h3')
	->text(Language::get('preview', '_preview'));
$linkArray = array(
	'rs-link-default',
	'rs-link-readmore'
);
$titleArray = array(
	'rs-title-content',
	'rs-title-content-sub',
	'rs-title-comment',
	'rs-title-extra'
);
$paragraphContent = 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua';
?>

<!-- several links -->

<?php foreach ($linkArray as $value): ?>

	<?php echo $titlePartialElement->text('.' . $value); ?>
	<?php echo $linkElement->copy()->addClass($value); ?>

<?php endforeach; ?>

<!-- placeholder text with link -->

<?php echo $titlePartialElement->text(Language::get('content')); ?>
<?php echo $paragraphElement->copy()->html($paragraphContent . ' ' . $linkElement->addClass('rs-link-default') . ' ' . $paragraphContent); ?>

<!-- several titles -->

<?php foreach ($titleArray as $value): ?>

	<?php echo $titlePartialElement->text('.' . $value); ?>
	<?php echo $titleElement->copy()->addClass($value); ?>

<?php endforeach; ?>
