<?php namespace Redaxscript\Template; ?>

<!DOCTYPE html>
<html lang="<?php echo Tag::getRegistry('language'); ?>" dir="<?php echo Helper::getDirection(); ?>" class="<?php echo Helper::getClass(); ?>">

	<!-- head -->

	<head>
		<?php echo Tag::partial(
		[
			'templates/admin/head.phtml',
			'templates/website/head.phtml'
		]); ?>
	</head>

	<!-- body -->

	<?php if (!Tag::getRegistry('fullRoute')): ?>
		<body class="rs-body-homepage">
	<?php else: ?>
		<body class="rs-body">
	<?php endif; ?>
		<?php $body = Tag::partial(
		[
			Tag::getRegistry('fullRoute') ? 'templates/website/header.phtml' : null,
			'templates/website/main.phtml',
			Tag::getRegistry('fullRoute') ? 'templates/default/footer.phtml' : null,
			'templates/admin/script.phtml',
			'templates/default/script.phtml'
		]); ?>
		<?php echo Tag::partial('templates/admin/panel.phtml'); ?>
		<?php echo Tag::partial('templates/default/menu-status.phtml'); ?>
		<div class="rs-has-menu">
			<?php echo $body; ?>
		</div>
	</body>
</html>
