<?php namespace Redaxscript\Template; ?>

<!-- homepage -->

<?php if (!Tag::registry('fullRoute')): ?>
	<main class="rs-fn-clearfix">
		<?php echo Tag::extraRaw()
			->where('alias', 'homepage')
			->findOne()
			->text; ?>

		<!-- feature -->

		<div class="rs-box-feature">
			<?php echo Tag::articleRaw()
				->where('alias', 'features')
				->findOne()
				->text; ?>
			<a href="features" class="rs-button-default rs-is-large">Explore more</a>
		</div>
	</main>

<!-- else default -->

<?php else: ?>
	<main id="main" class="rs-main rs-fn-clearfix">

		<!-- handle content error -->

		<?php if (Tag::registry('contentError')): ?>
			<div class="rs-wrapper rs-wrapper-page rs-fn-clearfix">
				<?php echo Tag::partial('templates/default/error.phtml'); ?>
			</div>

		<!-- else content and sidebar -->

		<?php elseif (Tag::registry('firstParameter') === 'documentation'): ?>
			<div class="rs-wrapper rs-wrapper-page rs-has-sidebar rs-fn-clearfix">
				<?php echo Tag::partial(
				[
					'templates/default/content.phtml',
					'templates/website/sidebar.phtml'
				]); ?>
			</div>

		<!-- else content -->

		<?php else: ?>
			<div class="rs-wrapper rs-wrapper-page rs-fn-clearfix">
				<?php echo Tag::partial('templates/default/content.phtml'); ?>
			</div>
		<?php endif; ?>
	</main>
<?php endif; ?>