<?php namespace Redaxscript\Template; ?>

<!-- logic -->

<input id="menu" class="rs-fn-status-menu" type="checkbox"/>
<label class="rs-fn-toggle-menu rs-label-toggle-menu" for="menu">Menu</label>
<label class="rs-fn-close-menu rs-label-close-menu" for="menu"></label>

<!-- list -->

<?php echo Tag::navigation('categories',
[
	'class' => 'rs-fn-dropdown rs-fn-menu rs-list-menu',
	'limit' => 5
]); ?>