<?php namespace Redaxscript\Template; ?>

<!-- article -->

<?php $categoryId = Helper::getRegistry('categoryId'); ?>
<?php $articleId = Helper::getRegistry('articleId'); ?>
<?php if ($categoryId || $articleId): ?>
	<section class="rs-section-article">
		<?php echo Tag::article($categoryId, $articleId); ?>
		<?php if ($categoryId): ?>
			<?php echo Tag::pagination('articles', $categoryId); ?>
		<?php endif; ?>
	</section>
<?php endif; ?>

