<?php namespace Redaxscript\Template; ?>

<!-- header -->

<?php echo Tag::partial('templates/default/header.phtml'); ?>

<!-- main -->

<main id="main" class="rs-main rs-fn-clearfix">

	<!-- teaser -->

	<?php if (!Tag::registry('adminParameter')): ?>
		<?php echo Tag::extra(
		[	
			'filter' => 'teaser'
		]); ?>
	<?php endif; ?>

	<!-- page -->

	<div class="rs-wrapper rs-wrapper-page rs-fn-clearfix">

		<!-- handle content error -->

		<?php if (Tag::registry('contentError')): ?>
			<?php echo Tag::partial('templates/default/error.phtml'); ?>

			<!-- else content and sidebar -->

		<?php else: ?>
			<?php echo Tag::partial(
			[	
				'templates/default/content.phtml',
				'templates/default/sidebar.phtml'
			]); ?>
		<?php endif; ?>
	</div>
</main>

<!-- footer -->

<?php echo Tag::partial('templates/default/footer.phtml'); ?>

<!-- bottom script -->

<?php echo Tag::script()
	->appendFile('//ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js');
?>

<!--@todo: extend the Tag::script to load all the scripts from .loader - delete the file after that !-->
