<?php namespace Redaxscript\Template; ?>

<!-- header -->

<?php echo Tag::partial('templates/default/header.phtml'); ?>

<!-- main -->

<main id="main" class="rs-main rs-fn-clearfix">

	<!-- teaser -->

	<?php if (!Tag::registry('adminParameter')): ?>
		<?php echo Tag::extra(
		[	
			'filter' => 'teaser'
		]); ?>
	<?php endif; ?>

	<!-- handle content error -->

	<?php if (Tag::registry('contentError')): ?>
		<div class="rs-wrapper rs-wrapper-page rs-fn-clearfix">
			<?php echo Tag::partial('templates/default/error.phtml'); ?>
		</div>

	<!-- else content and sidebar -->

	<?php else: ?>
		<div class="rs-wrapper rs-wrapper-page rs-has-sidebar rs-fn-clearfix">
			<?php echo Tag::partial(
			[
				'templates/default/content.phtml',
				'templates/default/sidebar.phtml'
			]); ?>
		</div>
	<?php endif; ?>

</main>

<!-- footer -->

<?php echo Tag::partial('templates/default/footer.phtml'); ?>

<!-- foot script -->

<?php echo Tag::partial('templates/admin/script.phtml'); ?>
<?php echo Tag::partial('templates/default/script.phtml'); ?>
