<?php namespace Redaxscript\Template; ?>

<!-- footer -->

<footer id="footer" class="rs-footer">
	<div class="rs-wrapper">
		<span class="rs-text-about">
			<?php echo Helper::getLanguage('powered_by'); ?>
			<a href="<?php echo Helper::getLanguage('_package')['homepage']; ?>" class="rs-link-homepage">
				<?php echo Helper::getLanguage('_package')['name']; ?>
			</a>
			<?php echo Helper::getLanguage('_package')['version']; ?>
		</span>
		<a class="rs-link-login" href="<?php echo Helper::getRegistry('parameterRoute'); ?>login">
			<?php echo Helper::getLanguage('login'); ?>
		</a>
	</div>
</footer>
