<?php use Redaxscript\Template as Template; ?>

<!-- footer -->

<?php if (!Template::registry('myMobile')): ?>
	<footer id="rs-footer" class="rs-footer">
		<section class="rs-wrapper rs-clearfix">
			<?php echo Template::extra('footer'); ?>
		</section>

		<!-- bottom -->

		<div id="rs-bottom" class="rs-bottom">
			<section class="rs-wrapper">
				<?php echo Template::language('powered_by'); ?>
				<a href="<?php echo Template::language('homepage', '_package'); ?>" class="rs-link-custom rs-link-powered-by"><?php echo Template::language('name', '_package'); ?></a>
				<?php echo Template::language('version', '_package'); ?>
			</section>
		</div>

	</footer>
<?php endif; ?>
