<?php use Redaxscript\Template as Template; ?>

<!-- base and title -->

<?php echo Template::base(); ?>
<?php echo Template::title(); ?>

<!-- meta -->

<?php echo Template::meta(); ?>
<meta name="viewport" content="width=device-width" />

<!-- link -->

<?php echo Template::link(); ?>
<link href="templates/default/images/favicon.ico" rel="shortcut icon" />
<?php if (!Template::registry('myMobile')): ?>
	<link href="//fonts.googleapis.com/css?family=PT+Sans+Narrow<?php echo urlencode('|'); ?>Open+Sans&amp;subset=<?php echo Template::helperSubset(); ?>" rel="stylesheet" />
<?php endif; ?>

<!-- style and script -->

<?php echo Template::style(); ?>
<?php echo Template::script('init'); ?>