<?php namespace Redaxscript\Template; ?>

<!-- base -->

<?php echo Tag::base(); ?>

<!-- title -->

<?php echo Tag::title(); ?>

<!-- meta -->

<?php echo Tag::meta()
		->init()
		->append('charset', Tag::setting('charset'))
		->append(['name' => 'author', 'content' => Tag::setting('author')])
		->append(['name' => 'generator', 'content' => Tag::language('name', '_package') . ' ' . Tag::language('version', '_package')])
		->append(['name' => 'description', 'content' => Helper::getDescription()])
		->append(['name' => 'robots', 'content' => Helper::getRobots()])
		->append(['name' => 'viewport', 'content' => 'width=device-width'])
		->append(['name' => 'theme-color', 'content' => '#323e4c'])
		->append(['name' => 'msapplication-navbutton-color', 'content' => '#323e4c'])
		->append(['name' => 'apple-mobile-web-app-status-bar-stylecontent', 'content' => '#323e4c']); ?>

<!-- link -->

<?php echo Tag::link()
		->init()
		->append(['href' => Tag::registry('root') . '/' . Helper::getCanonical(), 'rel' => 'canonical'])
		->append(['href' => 'templates/default/assets/images/favicon.ico', 'rel' => 'shortcut icon'])
		->append(['href' => 'templates/default/assets/images/favicon.png', 'rel' => 'apple-touch-icon'])
		->appendFile('//fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700&amp;subset=' . Helper::getSubset())
		->appendFile('dist/styles/base.min.css')
		->appendFile('templates/default/dist/styles/default.min.css'); ?>

<!-- head script -->

<?php echo Tag::script()
	->init('head')
	->prependFile('templates/default/assets/scripts/init.js')
	->prependFile('assets/scripts/init.js')
	->prependFile('assets/scripts/support.js')
	->appendInline(Helper::getTransport());
?>