<?php namespace Redaxscript\Template; ?>

<!-- header -->

<header id="header" class="rs-header">
	<section class="rs-wrapper">

		<div class="rs-box-header">

			<!-- title -->

			<?php if (Tag::setting('title')): ?>
				<h1 class="rs-title-header">
					<a href="<?php echo Tag::registry('root'); ?>">
						<?php echo Tag::setting('title'); ?>
					</a>
				</h1>
			<?php endif; ?>

			<!-- description -->

			<?php if (Tag::setting('description')): ?>
				<span class="rs-text-header" title="<?php echo Tag::setting('description'); ?>"><?php echo Tag::setting('description'); ?></span>
			<?php endif; ?>
		</div>

		<!-- menu -->

		<?php echo Tag::partial('templates/default/menu.phtml'); ?>
	</section>
</header>
