<?php namespace Redaxscript\Template; ?>

<!-- base -->

<?php echo Tag::base(); ?>

<!-- title -->

<?php echo Tag::title(); ?>

<!-- meta -->

<?php Tag::meta()->append(['charset' => Tag::setting('charset')]); ?>
<?php Tag::meta()->append(['name' => 'author', 'content' => Tag::setting('author')]); ?>
<?php Tag::meta()->append(['name' => 'generator', 'content' => Tag::language('name', '_package') . ' ' . Tag::language('version', '_package')]); ?>
<?php Tag::meta()->append(['name' => 'description', 'content' => Helper::getDescription()]); ?>
<?php Tag::meta()->append(['name' => 'robots', 'content' => Helper::getRobots()]); ?>
<?php Tag::meta()->append(['name' => 'viewport', 'content' => 'width=device-width']); ?>
<?php Tag::meta()->append(['name' => 'theme-color', 'content' => '#323e4c']); ?>
<?php Tag::meta()->append(['name' => 'msapplication-navbutton-color', 'content' => '#323e4c']); ?>
<?php Tag::meta()->append(['name' => 'apple-mobile-web-app-status-bar-stylecontent', 'content' => '#323e4c']); ?>
<?php echo Tag::meta();
?>

<!-- link -->

<?php Tag::link()->append(['href' => Tag::registry('root') . '/' . Helper::getCanonical()]); ?>
<?php Tag::link()->append(['href' => 'templates/default/assets/images/favicon.ico', 'rel' => 'shortcut icon']); ?>
<?php Tag::link()->append(['href' => 'templates/default/assets/images/favicon.png', 'rel' => 'apple-touch-icon']); ?>
<?php Tag::link()->append(['href' => '//fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700&amp;subset=' . Helper::getSubset(), 'rel' => 'stylesheet']); ?>
<?php echo Tag::link(); ?>

<!-- style and script -->

<?php echo Tag::style(); ?>
<?php echo Tag::scriptTmp('init'); ?>
