<?php namespace Redaxscript\Template; ?>

<!DOCTYPE html>
<html lang="<?php echo Tag::registry('language'); ?>" dir="<?php echo Helper::getDirection(); ?>" class="<?php echo Helper::getClass(); ?>">

	<!-- head -->

	<head>
		<?php echo Tag::partial(
		[
			'templates/admin/head.phtml',
			'templates/default/head.phtml'
		]); ?>
	</head>

	<!-- body -->

	<body class="rs-body">
		<?php $body = Tag::partial('templates/default/body.phtml'); ?>
		<?php echo Tag::partial('templates/admin/panel.phtml'); ?>
		<?php echo $body; ?>
	</body>
</html>
