<!DOCTYPE html>
<?php include_once('helper.phtml'); ?>
<html lang="<?php echo LANGUAGE; ?>" class="<?php helper_class(); ?>">
	<head>
		<?php head(); ?>
		<meta name="viewport" content="width=device-width" />
		<?php scripts('startup'); ?>
		<?php styles(); ?>
		<link type="text/css" href="http://fonts.googleapis.com/css?family=Cuprum&amp;subset=latin,cyrillic" rel="stylesheet" />
		<link href="<?php echo ROOT; ?>/templates/default/images/touchicon.png" rel="apple-touch-icon-precomposed" />
		<link href="templates/default/images/favicon.ico" rel="shortcut icon" />
	</head>
	<body class="wrapper_body">
		<?php if (LOGGED_IN == TOKEN && FIRST_PARAMETER != 'logout'): ?>
			<?php include_once('templates/admin/panel.phtml'); ?>
		<?php endif; ?>
		<?php include_once('header.phtml'); ?>
		<div class="wrapper clear_fix">
			<?php if (DB_CONNECTED && CONTENT_ERROR && CENTER_BREAK == ''): ?>
				<?php include_once('error.phtml'); ?>
			<?php else: ?>
				<?php include_once('navibar.phtml'); ?>
				<?php include_once('content.phtml'); ?>
				<?php include_once('sidebar.phtml'); ?>
			<?php endif; ?>
		</div>
		<?php include_once('footer.phtml'); ?>
		<?php scripts(); ?>
	</body>
</html>