<?php namespace Redaxscript\Template; ?>

<!-- main -->

<main id="main" class="rs-main">

	<!-- teaser -->

	<?php if (!Helper::getRegistry('adminParameter')): ?>
		<?php echo include('default/helper/teaser.php'); ?>
	<?php endif; ?>

	<!-- error -->

	<?php if (Helper::getResponseCode() === 404): ?>
		<div class="rs-wrapper rs-wrapper-page">
			<?php echo Tag::partial('default/error.phtml'); ?>
		</div>

	<!-- else content and sidebar -->

	<?php else: ?>
		<div class="rs-wrapper rs-wrapper-page rs-has-sidebar">
			<?php echo Tag::partial(
			[
				'default/content.phtml',
				'default/sidebar.phtml'
			]); ?>
		</div>
	<?php endif; ?>

</main>