<?php namespace Redaxscript\Template; ?>

<!-- logic -->

<label class="rs-fn-toggle-menu rs-label-toggle-menu" for="status-menu">Menu</label>
<label class="rs-fn-close-menu rs-label-close-menu" for="status-menu"></label>

<!-- list -->

<ul class="rs-fn-dropdown rs-fn-menu rs-list-menu">
	<li>
		<span><?php echo Tag::getLanguage('categories'); ?></span>
		<?php echo Tag::navigation('categories',
		[
			'className' =>
			[
				'list' => 'rs-list-menu-children'
			],
			'limit' => 5
		]); ?>
	</li><li>
		<span><?php echo Tag::getLanguage('articles'); ?></span>
		<?php echo Tag::navigation('articles',
		[
			'className' =>
			[
				'list' => 'rs-list-menu-children'
			],
			'limit' => 5
		]); ?>
	</li>
</ul>