<nav id="navibar" class="navibar grid_space s2o7">
	<div class="box_navibar">

		<!-- donate -->

		<?php if (LOGGED_IN === TOKEN && FIRST_PARAMETER !== 'logout'): ?>
			<?php echo anchor_element('external', '', 'button_default button_donate', 'Donate', 'http://redaxscript.com/donate'); ?>

		<!-- else login -->

		<?php elseif (DB_CONNECTED): ?>
			<?php echo anchor_element('internal', '', 'button_default button_login', l('login'), 'login'); ?>
		<?php endif; ?>

		<!-- support -->

		<?php echo anchor_element('external', '', 'button_default button_support', 'Support', 'http://redaxscript.com/support'); ?>
	</div>
</nav>