<?php namespace Redaxscript\Admin\Template; ?>

<?php if (Tag::registry('loggedIn') === Tag::registry('token') && Tag::registry('firstParameter') !== 'logout'): ?>

	<!-- link -->

	<?php Tag::link()
		->init('admin')
		->appendFile('//fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700&amp;subset=' . Helper::getSubset())
		->appendFile('templates/admin/dist/styles/admin.min.css')
		->rewrite(
		[
			'url(../fonts' => 'url(../../templates/admin/dist/fonts'
		])
		->concat(); ?>

	<!-- head script -->

	<?php Tag::script()
		->init('head')
		->appendFile('templates/admin/assets/scripts/init.js');	?>
<?php endif; ?>

