<?php use Redaxscript\Template as Template; ?>

<?php if (Template::registry('loggedIn') === Template::registry('token') && Template::registry('firstParameter') !== 'logout'): ?>
	<nav id="panel-admin" class="admin-js-panel-admin admin-panel-admin">
		<div class="admin-box-panel-admin">
			<section class="admin-wrapper rs-clearfix">
				<?php echo Template::adminPanel(); ?>
			</section>
		</div>
	</nav>
<?php endif; ?>