<?php use Redaxscript\Template as Template; ?>

<?php if (Template::registry('loggedIn') === Template::registry('token') && Template::registry('firstParameter') !== 'logout'): ?>
	<nav id="panel-admin" class="rs-admin-js-panel rs-admin-panel">
		<div class="rs-admin-box-panel">
			<section class="rs-admin-wrapper rs-admin-clearfix">
				<?php echo Template::adminPanel(); ?>
			</section>
		</div>
	</nav>
<?php endif; ?>