<?php namespace Redaxscript\Admin\Template; ?>

<!-- foot script -->

<?php if (Tag::getRegistry('loggedIn') === Tag::getRegistry('token') && Tag::getRegistry('firstParameter') !== 'logout'): ?>
	<?php Tag::script()
		->init('foot')
		->appendFile('https://cdnjs.cloudflare.com/ajax/libs/speakingurl/13.0.0/speakingurl.min.js')
		->appendFile('templates/admin/assets/scripts/init.js')
		->appendFile('templates/admin/dist/scripts/admin.min.js');
	?>
<?php endif; ?>