CREATE TABLE IF NOT EXISTS /* %PREFIX% */articles (
	id SERIAL PRIMARY KEY,
	title varchar(255),
	alias varchar(255),
	author varchar(255),
	description varchar(255),
	keywords varchar(255),
	robots int,
	text text,
	language char(2),
	template varchar(255),
	sibling int,
	category int,
	headline int DEFAULT 1,
	byline int DEFAULT 1,
	comments int DEFAULT 0,
	status int DEFAULT 1,
	rank int,
	access varchar(255),
	date int
);
