<?php namespace Redaxscript; ?>

<div id="rs-teaser" class="rs-teaser">
	<div class="rs-wrapper">
		<h3 class="rs-title-teaser"><span class="rs-text-first-line">Start your own project right <span class="rs-text-important">now</span>,</span> don&rsquo;t panic about <span class="rs-text-important">responsive</span> &ndash; it&rsquo;s all in!</h3>
		<div class="rs-box-navibar">
			<a href="donate" class="rs-button-default rs-button-donate">Donate</a>
			<a href="support" class="rs-button-default rs-button-support">Support</a>
		</div>
	</div>
</div>