<?php namespace Redaxscript\Template; ?>

<!DOCTYPE html>
<html lang="<?php echo Helper::getRegistry('language'); ?>" dir="<?php echo Helper::getDirection(); ?>" class="<?php echo Helper::getClass('rs-is-'); ?>">

	<!-- head -->

	<head>
		<?php echo Tag::partial(
		[
			'admin/head.phtml',
			'default/head.phtml'
		]); ?>
	</head>

	<!-- body -->

	<body class="rs-body">

		<!-- logic -->

		<input id="menu" class="rs-fn-status-menu" type="checkbox" />

		<?php $body = Tag::partial(
		[
			'default/header.phtml',
			'wide/main.phtml',
			'default/footer.phtml',
			'admin/script.phtml',
			'default/script.phtml'
		]); ?>
		<?php echo Tag::partial('admin/panel.phtml'); ?>
		<?php echo Tag::partial('default/menu-status.phtml'); ?>
		<div class="rs-has-menu">
			<?php echo $body; ?>
		</div>
	</body>
</html>
