<!DOCTYPE html>
<?php include_once('templates/default/helper.phtml'); ?>
<html lang="en" class="<?php helper_class(); ?>">
	<head>
		<?php head(); ?>
		<meta name="viewport" content="width=device-width" />
		<?php scripts('startup'); ?>
		<?php styles(); ?>
		<link href="<?php echo ROOT; ?>/templates/default/images/touchicon.png" rel="apple-touch-icon-precomposed" />
		<link href="templates/default/images/favicon.ico" rel="shortcut icon" />
	</head>
	<body class="wrapper_body">
		<?php if (LOGGED_IN == TOKEN && FIRST_PARAMETER != 'logout'): ?>
			<?php include_once('templates/admin/panel.phtml'); ?>
		<?php endif; ?>
		<?php include_once('templates/default/header.phtml'); ?>
		<div class="wrapper clear_fix">
			<?php if (DB_CONNECTED && CONTENT_ERROR && CENTER_BREAK == ''): ?>
				<?php include_once('templates/default/error.phtml'); ?>
			<?php else: ?>
				<?php include_once('content.phtml'); ?>
			<?php endif; ?>
		</div>
		<?php include_once('templates/default/footer.phtml'); ?>
		<?php if (MY_MOBILE == ''): ?>
			<script>r.loadFont('http://fonts.googleapis.com/css?family=PT+Sans+Narrow|Open+Sans&amp;subset=<?php helper_subset(); ?>');</script>
		<?php endif; ?>
		<?php scripts(); ?>
	</body>
</html>