<?php namespace Redaxscript\Template; ?>

<!-- main -->

<main id="main" class="rs-main">

	<!-- page -->

	<div class="rs-wrapper rs-wrapper-page">

		<!-- bad response -->

		<?php if (Helper::getResponseCode() === 404): ?>
			<?php echo Tag::partial('default/error.phtml'); ?>

		<!-- else content -->

		<?php else: ?>
			<?php echo Tag::partial('default/content.phtml'); ?>
		<?php endif; ?>
	</div>
</main>
