<?php namespace Redaxscript\Template; ?>

<!-- main -->

<main id="main" class="rs-main rs-fn-clearfix">

	<!-- page -->

	<div class="rs-wrapper rs-wrapper-page rs-fn-clearfix">

		<!-- handle content error -->

		<?php if (Tag::getRegistry('contentError')): ?>
			<?php echo Tag::partial('templates/default/error.phtml'); ?>

		<!-- else content -->

		<?php else: ?>
			<?php echo Tag::partial('templates/default/content.phtml'); ?>
		<?php endif; ?>
	</div>
</main>