<?php namespace Redaxscript\Template; ?>

<!-- base -->

<?php echo Tag::base(); ?>

<!-- title -->

<?php echo Tag::title(Helper::getLanguage('installation')); ?>

<!-- meta -->

<?php echo Tag::meta()
	->init()
	->append('charset', 'utf-8')
	->append(['name' => 'viewport', 'content' => 'width=device-width'])
	->append(['name' => 'theme-color', 'content' => '#323e4c'])
	->append(['name' => 'msapplication-navbutton-color', 'content' => '#323e4c'])
	->append(['name' => 'apple-mobile-web-app-status-bar-stylecontent', 'content' => '#323e4c']); ?>

<!-- link -->

<?php echo Tag::link()
	->init()
	->append(['href' => 'templates/default/assets/images/favicon.ico', 'rel' => 'shortcut icon'])
	->append(['href' => 'templates/default/assets/images/favicon.png', 'rel' => 'apple-touch-icon'])
	->append(['href' => 'https://fonts.gstatic.com', 'rel' => 'preconnect'])
	->appendFile(
	[
		'https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:wght@300;700&amp;subset=' . Helper::getSubset(),
		'templates/install/dist/styles/install.min.css'
	])
	->rewrite(
	[
		'../../../../templates' => '../../templates'
	])
	->concat(); ?>

<!-- head script -->

<?php echo Tag::script()
	->init('head')
	->prependInline(Helper::getContent(
	[
		'assets/scripts/init.js',
		'templates/install/assets/scripts/init.js'
	]))
	->transportVar('rs', Helper::getTransport())
	->concat(); ?>
