<?php namespace Redaxscript\Template; ?>

<!-- title -->

<title><?php echo Tag::language('installation'); ?></title>

<!-- meta -->

<?php
Tag::meta()->append(['name' => 'viewport', 'content' => 'width=device-width']);
Tag::meta()->append(['name' => 'theme-color', 'content' => '#323e4c']);
Tag::meta()->append(['name' => 'msapplication-navbutton-color', 'content' => '#323e4c']);
Tag::meta()->append(['name' => 'apple-mobile-web-app-status-bar-stylecontent', 'content' => '#323e4c']);
echo Tag::meta();
?>

<!-- link -->

<?php
Tag::link()->append(['href' => 'templates/default/assets/images/favicon.ico', 'rel' => 'shortcut icon']);
Tag::link()->append(['href' => 'templates/default/assets/images/favicon.png', 'rel' => 'apple-touch-icon']);
Tag::link()->append(['href' => '//fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700&amp;subset=' . Helper::getSubset(), 'rel' => 'stylesheet']);
echo Tag::link();
?>

<!-- style and script -->

<?php echo Tag::style(); ?>
<?php echo Tag::scriptTmp('init'); ?>
