<?php namespace Redaxscript\Template; ?>

<!DOCTYPE html>
<html lang="<?php echo Tag::getRegistry('language'); ?>" dir="<?php echo Helper::getDirection(); ?>" class="<?php echo Helper::getClass(); ?>">

	<!-- head -->

	<head>
		<?php echo Tag::partial('templates/install/head.phtml'); ?>
	</head>

	<!-- body -->

	<body class="rs-install-body">

		<!-- main -->

		<main id="main" class="rs-install-main rs-install-wrapper">
			<h1 class="rs-install-title"><?php echo Tag::getLanguage('name', '_package'); ?></h1>
			<?php echo Tag::partial('templates/install/content.phtml'); ?>
		</main>

		<!-- foot script -->

		<?php echo Tag::partial('templates/install/script.phtml'); ?>
	</body>
</html>