<?php namespace Redaxscript\Template; ?>

<!DOCTYPE html>
<html lang="<?php echo Helper::getRegistry('language'); ?>" dir="<?php echo Helper::getDirection(); ?>" class="<?php echo Helper::getClass('rs-is-'); ?>">

	<!-- head -->

	<head>
		<?php echo Tag::partial('install/head.phtml'); ?>
	</head>

	<!-- body -->

	<body class="rs-install-body">

		<!-- main -->

		<main id="main" class="rs-install-main rs-install-wrapper">
			<h1 class="rs-install-title"><?php echo Helper::getLanguage('_package')['name']; ?></h1>
			<?php echo Tag::partial('install/content.phtml'); ?>
		</main>

		<!-- foot script -->

		<?php echo Tag::partial('install/script.phtml'); ?>
	</body>
</html>