<?php use Redaxscript\Template as Template; ?>

<!DOCTYPE html>
<html lang="<?php echo Template::registry('language'); ?>" class="<?php echo Template::helperClass(); ?>">

	<!-- head -->

	<head>
		<?php echo Template::partial('templates/default/head.phtml'); ?>
	</head>

	<!-- body -->

	<body class="rs-wrapper-body">

		<!-- main -->

		<div class="rs-wrapper rs-clearfix">
			<?php echo Template::partial('templates/install/content.phtml'); ?>
		</div>

		<!-- footer -->

		<?php echo Template::script(); ?>
	</body>
</html>