<?php namespace Redaxscript; ?>

<!DOCTYPE html>
<html lang="<?php echo Registry::get('language'); ?>" class="<?php echo Template::helperClass(); ?>">

	<!-- head -->

	<head>
		<?php echo Template::partial('templates/default/head.phtml'); ?>
	</head>

	<!-- body -->

	<body class="wrapper_body">

		<!-- main -->

		<div class="wrapper clearfix">
			<?php echo Template::partial('templates/install/content.phtml'); ?>
		</div>

		<!-- footer -->

		<?php echo Template::script(); ?>
	</body>
</html>