<?php namespace Redaxscript\Template; ?>

<!DOCTYPE html>
<html lang="<?php echo Tag::registry('language'); ?>" dir="<?php echo Helper::getDirection(); ?>" class="<?php echo Helper::getClass(); ?>">

	<!-- head -->

	<head>
		<?php echo Tag::partial('templates/install/head.phtml'); ?>
	</head>

	<!-- body -->

	<body class="rs-body rs-install-body rs-wrapper-body">

		<!-- main -->

		<main id="main" class="rs-install-main rs-install-wrapper rs-fn-clearfix">
			<h1 class="rs-install-title"><?php echo Tag::language('name', '_package'); ?></h1>
			<?php echo Tag::partial('templates/install/content.phtml'); ?>
		</main>

		<!-- footer -->

		<?php echo Tag::scriptTmp(); ?>
	</body>
</html>