<div class="box_first grid_space s1o5">
	<h3 class="title_footer">
		<a href="http://redaxscript.com/general" title="General">General</a>
	</h3>
	<ul class="list_footer">
		<li>
			<a href="http://redaxscript.com/general/introduction" title="Introduction">Introduction</a>
		</li>
		<li>
			<a href="http://redaxscript.com/general/feature-list" title="Feature list">Feature list</a>
		</li>
		<li>
			<a href="http://redaxscript.com/general/benchmark" title="Benchmark">Benchmark</a>
		</li>
		<li>
			<a href="http://redaxscript.com/general/about" title="About">About</a>
		</li>
	</ul>
</div>

<div class="box_second grid_space s1o5">
	<h3 class="title_footer">
		<a href="http://redaxscript.com/download" title="Download">Download</a>
	</h3>
	<ul class="list_footer">
		<li>
			<a href="http://redaxscript.com/download/releases" title="Releases">Releases</a>
		</li>
		<li>
			<a href="http://redaxscript.com/download/templates" title="Templates">Templates</a>
		</li>
		<li>
			<a href="http://redaxscript.com/download/languages" title="Languages">Languages</a>
		</li>
		<li>
			<a href="http://redaxscript.com/download/modules" title="Modules">Modules</a>
		</li>
	</ul>
</div>

<div class="box_third grid_space s1o5">
	<h3 class="title_footer">
		<a href="http://redaxscript.com/support" title="Support">Support</a>
	</h3>
	<ul class="list_footer">
		<li>
			<a href="http://redaxscript.com/support/getting-started" title="Getting started">Getting started</a>
		</li>
		<li>
			<a href="http://redaxscript.com/support/installation-guide" title="Installation guide">Installation guide</a>
		</li>
		<li>
			<a href="http://redaxscript.com/support/troubleshooting" title="Troubleshooting">Troubleshooting</a>
		</li>
		<li>
			<a href="http://redaxscript.com/support/faq" title="FAQ">FAQ</a>
		</li>
	</ul>
</div>

<div class="box_fourth grid_space s1o5">
	<h3 class="title_footer">
		<a href="http://redaxscript.com/develop" title="Develop">Develop</a>
	</h3>
	<ul class="list_footer">
		<li>
			<a href="http://redaxscript.com/develop/source-code" title="Source code">Source code</a>
		</li>
		<li>
			<a href="http://redaxscript.com/develop/github-guide" title="Github guide">Github guide</a>
		</li>
		<li>
			<a href="http://redaxscript.com/develop/documentation" title="Documentation">Documentation</a>
		</li>
		<li>
			<a href="http://redaxscript.com/develop/roadmap" title="Roadmap">Roadmap</a>
		</li>
		<li>
			<a href="http://redaxscript.com/develop/changelog" title="Changelog">Changelog</a>
		</li>
	</ul>
</div>

<div class="box_last grid_space s1o5">
	<h3 class="title_footer">
		<a href="http://redaxscript.com/community" title="Community">Community</a>
	</h3>
	<ul class="list_footer">
		<li>
			<a href="http://redaxscript.com/community/facebook-group" title="Facebook group">Facebook group</a>
		</li>
		<li>
			<a href="http://redaxscript.com/community/team" title="Team">Team</a>
		</li>
		<li>
			<a href="http://redaxscript.com/community/contribute" title="Contribute">Contribute</a>
		</li>
	</ul>
</div>
