<?php namespace Redaxscript\Template; ?>

<!-- header -->

<?php echo Tag::partial('templates/skeleton/header.phtml'); ?>

<!-- main -->

<main id="main" class="rs-main rs-fn-clearfix">

	<!-- handle content error -->

	<?php if (Tag::registry('contentError')): ?>
		<div class="rs-wrapper rs-fn-clearfix">
			<?php echo Tag::partial('templates/skeleton/error.phtml'); ?>
		</div>

	<!-- else content and sidebar -->

	<?php else: ?>
		<div class="rs-wrapper rs-has-sidebar rs-fn-clearfix">
			<?php echo Tag::partial(
			[
				'templates/skeleton/content.phtml',
				'templates/skeleton/sidebar.phtml'
			]); ?>
		</div>
	<?php endif; ?>

</main>

<!-- footer -->

<?php echo Tag::partial('templates/skeleton/footer.phtml'); ?>

<!-- foot script -->

<?php echo Tag::partial('templates/admin/script.phtml'); ?>
<?php echo Tag::partial('templates/skeleton/script.phtml'); ?>

