<?php namespace Redaxscript\Template; ?>

<!-- header -->

<?php echo Tag::partial('templates/skeleton/header.phtml'); ?>

<!-- main -->

<main id="main" class="rs-main rs-wrapper rs-fn-clearfix">

	<!-- handle content error -->

	<?php if (Tag::registry('contentError')): ?>
		<?php echo Tag::partial('templates/skeleton/error.phtml'); ?>

	<!-- else content and sidebar -->

	<?php else: ?>
		<?php echo Tag::partial(
		[
			'templates/skeleton/content.phtml',
			'templates/skeleton/sidebar.phtml'
		]); ?>
	<?php endif; ?>

</main>

<!-- footer -->

<?php echo Tag::partial('templates/skeleton/footer.phtml'); ?>

<!-- foot script -->

<?php echo Tag::partial('templates/admin/script.phtml'); ?>
<?php echo Tag::script()
	->init('foot')
	->prependFile('assets/scripts/fallback.js')
	->prependFile('//ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->appendFile('assets/scripts/dialog.js')
	->appendFile('assets/scripts/form.js')
	->appendFile('assets/scripts/interface.js')
	->appendFile('assets/scripts/misc.js')
	->concat(); ?>
