<?php namespace Redaxscript\Template; ?>

<!-- footer -->

<footer id="footer" class="rs-footer">
	<div class="rs-wrapper rs-fn-clearfix">
		<span class="rs-text-about">
            <span class="rs-text-powered-by">
                <?php echo Tag::getLanguage('powered_by'); ?>
            </span>
            <a href="<?php echo Tag::getLanguage('homepage', '_package'); ?>" class="rs-link-footer">
				<?php echo Tag::getLanguage('name', '_package'); ?>
			</a>
			<?php echo Tag::getLanguage('version', '_package'); ?>
        </span>
		<a class="rs-link-login" href="<?php echo Tag::getRegistry('parameterRoute'); ?>login"><?php echo Tag::getLanguage('login'); ?></a>
	</div>
</footer>