<?php namespace Redaxscript\Template; ?>

<!-- footer -->

<footer id="footer" class="rs-footer">
	<div class="rs-wrapper">
		<span class="rs-text-about">
			<span class="rs-text-powered-by">
				<?php echo Helper::getLanguage('powered_by'); ?>
			</span>
			<a href="<?php echo Helper::getLanguage('homepage', '_package'); ?>" class="rs-link-footer">
				<?php echo Helper::getLanguage('name', '_package'); ?>
			</a>
			<?php echo Helper::getLanguage('version', '_package'); ?>
		</span>
		<a class="rs-link-login" href="<?php echo Helper::getRegistry('parameterRoute'); ?>login"><?php echo Helper::getLanguage('login'); ?></a>
	</div>
</footer>