<?php namespace Redaxscript\Template; ?>

<!-- base -->

<?php echo Tag::base(); ?>

<!-- title -->

<?php echo Tag::title(Helper::getTitle()); ?>

<!-- meta -->

<?php echo Tag::meta()
	->init()
	->append('charset', Helper::getSetting('charset'))
	->append(['name' => 'author', 'content' => Helper::getSetting('author')])
	->append(['name' => 'generator', 'content' => Helper::getLanguage('name', '_package') . ' ' . Helper::getLanguage('version', '_package')])
	->append(['name' => 'description', 'content' => Helper::getDescription()])
	->append(['name' => 'keywords', 'content' => Helper::getKeywords()])
	->append(['name' => 'robots', 'content' => Helper::getRobots()])
	->append(['name' => 'viewport', 'content' => 'width=device-width'])
	->append(['name' => 'theme-color', 'content' => '#000'])
	->append(['name' => 'msapplication-navbutton-color', 'content' => '#000'])
	->append(['name' => 'apple-mobile-web-app-status-bar-stylecontent', 'content' => '#000']); ?>

<!-- link -->

<?php echo Tag::link()
	->init()
	->append(['href' => Helper::getCanonical(), 'rel' => 'canonical'])
	->append(['href' => 'data:image/png;base64,', 'rel' => 'shortcut icon'])
	->appendFile(
	[
		'https://fonts.googleapis.com/css?family=Raleway:300,700&amp;subset=' . Helper::getSubset(),
		'templates/skeleton/dist/styles/skeleton.min.css'
	])
	->concat(); ?>

<?php echo Tag::link()->init('admin'); ?>

<!-- head script -->

<?php echo Tag::script()
	->init('head')
	->prependFile(
	[
		'templates/skeleton/assets/scripts/init.js',
		'assets/scripts/init.js'
	])
	->transportVar('rs', Helper::getTransport())
	->concat(); ?>