<?php namespace Redaxscript\Template; ?>

<!DOCTYPE html>
<html lang="<?php echo Tag::getRegistry('language'); ?>" dir="<?php echo Helper::getDirection(); ?>" class="<?php echo Helper::getClass(); ?>">

	<!-- head -->

	<head>
		<?php echo Tag::partial(
		[
			'templates/admin/head.phtml',
			'templates/skeleton/head.phtml'
		]); ?>
	</head>

	<!-- body -->

	<body class="rs-body">
		<?php $body = Tag::partial(
		[
			'templates/skeleton/header.phtml',
			'templates/skeleton/main.phtml',
			'templates/skeleton/footer.phtml',
			'templates/admin/script.phtml',
			'templates/skeleton/script.phtml'
		]); ?>
		<?php echo Tag::partial('templates/admin/panel.phtml'); ?>
		<?php echo $body; ?>
	</body>
</html>
