<?php namespace Redaxscript\Template; ?>

<!DOCTYPE html>
<html lang="<?php echo Helper::getRegistry('language'); ?>" dir="<?php echo Helper::getDirection(); ?>" class="<?php echo Helper::getClass('rs-is-'); ?>">

	<!-- head -->

	<head>
		<?php echo Tag::partial(
		[
			'admin/head.phtml',
			'skeleton/head.phtml'
		]); ?>
	</head>

	<!-- body -->

	<body class="rs-body">
		<?php $body = Tag::partial(
		[
			'skeleton/header.phtml',
			'skeleton/main.phtml',
			'skeleton/footer.phtml',
			'admin/script.phtml',
			'skeleton/script.phtml'
		]); ?>
		<?php echo Tag::partial('admin/panel.phtml'); ?>
		<?php echo $body; ?>
	</body>
</html>
