<?php namespace Redaxscript\Template; ?>

<!-- main -->

<main id="main" class="rs-main">

	<!-- error -->

	<?php if (Helper::getRegistry('contentError')): ?>
		<div class="rs-wrapper">
			<?php echo Tag::partial('skeleton/error.phtml'); ?>
		</div>

	<!-- else content and sidebar -->

	<?php else: ?>
		<div class="rs-wrapper rs-has-sidebar">
			<?php echo Tag::partial(
			[
				'skeleton/content.phtml',
				'skeleton/sidebar.phtml'
			]); ?>
		</div>
	<?php endif; ?>

</main>