<?php
namespace Redaxscript;
use Redaxscript\Modules\Dialog;

$language = Language::getInstance();
$dialog= $admin ? new Dialog\Admin\Dialog(Registry::getInstance(), Request::getInstance(), Language::getInstance(), Config::getInstance()) : new Dialog\Dialog(Registry::getInstance(), Request::getInstance(), Language::getInstance(), Config::getInstance());
$message = $language->get('_preview')['preview'];
?>

<!-- dialog -->

<?php echo $dialog->alert($message); ?>
<?php echo $dialog->confirm($message); ?>
<?php echo $dialog->prompt($message); ?>