<?php
namespace Redaxscript;

$registry = Registry::getInstance();
$language = Language::getInstance();
$id = uniqid($admin ? 'admin-form-' : 'form-');
$i = 0;
$formElement = $admin ? new Admin\Html\Form($registry, $language) : new Html\Form($registry, $language);
$formElement
	->init()
	->append('<ul><li>')
	->label($language->get('_number')[++$i],
	[
		'for' => $id . $i
	])
	->text(
	[
		'id' => $id . $i,
		'placeholder' => 'Placeholder',
		'required' => 'required'
	])
	->append('</li><li>')
	->label($language->get('_number')[++$i],
	[
		'for' => $id . $i
	])
	->text(
	[
		'disabled' => 'disabled',
		'id' => $id . $i,
		'placeholder' => 'Placeholder'
	])
	->append('</li><li>')
	->label($language->get('_number')[++$i],
	[
		'for' => $id . $i
	])
	->select(
	[
		1,
		2,
		3,
		4
	],
	[
		2
	],
	[
		'id' => $id . $i
	])
	->append('</li><li>')
	->label($language->get('_number')[++$i],
	[
		'for' => $id . $i
	])
	->select(
	[
		1,
		2,
		3,
		4
	],
	[
		2
	],
	[
		'disabled' => 'disabled',
		'id' => $id . $i
	])
	->append('</li><li>')
	->label($language->get('_number')[++$i],
	[
		'for' => $id . $i
	])
	->selectRange(
	[
		'min' => 1,
		'max' => 4
	],
	[
		2,
		3
	],
	[
		'id' => $id . $i,
		'multiple' => 'multiple',
		'required' => 'required',
		'size' => 4
	])
	->append('</li><li>')
	->label($language->get('_number')[++$i],
	[
		'for' => $id . $i
	])
	->selectRange(
	[
		'min' => 1,
		'max' => 4
	],
	[
		2,
		3
	],
	[
		'disabled' => 'disabled',
		'id' => $id . $i,
		'multiple' => 'multiple',
		'required' => 'required',
		'size' => 4
	])
	->append('</li><li>')
	->label($language->get('_number')[++$i],
	[
		'for' => $id . $i
	])
	->textarea(
	[
		'class' => $admin ? 'rs-admin-field-textarea rs-admin-field-small' : 'rs-field-textarea rs-field-small',
		'id' => $id . $i
	])
	->append('</li><li>')
	->label($language->get('_number')[++$i],
	[
		'for' => $id . $i
	])
	->textarea(
	[
		'class' => $admin ? 'rs-admin-field-textarea rs-admin-field-small' : 'rs-field-textarea rs-field-small',
		'disabled' => 'disabled',
		'id' => $id . $i
	])
	->append('</li><li>')
	->label($language->get('_number')[++$i],
	[
		'for' => $id . $i
	])
	->textarea(
	[
		'id' => $id . $i,
		'required' => 'required'
	])
	->append('</li><li>')
	->label($language->get('_number')[++$i],
	[
		'for' => $id . $i
	])
	->textarea(
	[
		'class' => $admin ? 'rs-admin-js-editor rs-admin-field-textarea rs-admin-field-small' : 'rs-js-editor rs-field-textarea rs-field-small',
		'id' => $id . $i
	])
	->append('</li></ul>')
	->submit()
	->reset();
?>

<!-- form -->

<?php echo $formElement; ?>
