<?php
namespace Redaxscript;

$imageElement = new Html\Element();
$imageElement->init('img',
[
	'alt' => 'image',
	'class' => 'rs-image-default',
	'loading' => 'lazy',
	'src' => 'https://cdn.redaxscript.com/unsplash/817/large.jpg'
]);
$videoElement = new Html\Element();
$videoElement->init('video',
[
	'autoplay' => 'autoplay',
	'class' => 'rs-video-default',
	'muted' => 'muted',
	'src' => 'https://cdn.redaxscript.com/renderfarming/bbb_sunflower_1080p_30fps_normal.mp4#10'
]);
?>

<!-- image -->

<?php echo $imageElement; ?>

<!-- video -->

<?php echo $videoElement; ?>