<?php
namespace Redaxscript;

$imageElement = new Html\Element();
$imageElement->init('img',
[
	'alt' => 'image',
	'class' => 'rs-image-default',
	'loading' => 'lazy',
	'src' => 'https://images.unsplash.com/photo-1523264897137-4cb31c04eaec?q=40&fm=webp&crop=faces&fit=crop&h=1000&w=2500'
]);
$videoElement = new Html\Element();
$videoElement->init('video',
[
	'autoplay' => 'autoplay',
	'class' => 'rs-video-default',
	'muted' => 'muted',
	'src' => 'http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4'
]);
?>

<!-- image -->

<?php echo $imageElement; ?>

<!-- video -->

<?php echo $videoElement; ?>