<?php namespace Redaxscript\Template; ?>

<article id="content" class="rs-console-install-content">
	<?php
		filter_var_array($_POST, FILTER_SANITIZE_STRING);
		$command = trim($_POST['command']);
		exec('php console.php ' . $command . " 2>&1", $execArray);
	?>

	<!-- code -->

	<pre class="rs-console-code"><?php echo htmlentities(implode($execArray, PHP_EOL)); ?></pre>

	<!-- form -->

	<form method="post" class="rs-console-form">
		<label for="prompt" class="rs-console-label"><?php echo Tag::registry('host'); ?>:~$</label>
		<input autofocus="autofocus" autocomplete="off" id="prompt" class="rs-console-field-text" size="60" name="command" />
	</form>
</article>