<?php namespace Redaxscript\Template; ?>

<article id="content" class="rs-console-install-content">
	<?php
		filter_var_array($_POST, FILTER_SANITIZE_STRING);
		$command = trim($_POST['command']);
		exec('php console.php ' . $command . " 2>&1", $execArray);
	?>

	<pre class="rs-console-output"><?php echo htmlentities(implode($execArray, PHP_EOL)); ?></pre>

	<form method="post" class="rs-console-form">
		<label for="prompt" class="rs-console-label"><?php echo $_SERVER['HTTP_HOST']; ?>:~$</label>
		<input autofocus="autofocus" id="prompt" size="60" name="command" class="rs-console-field-text" />
	</form>
</article>