<?php namespace Redaxscript\Template; ?>

<!-- base -->

<?php echo Tag::base(); ?>

<!-- title -->

<?php echo Tag::title(Helper::getLanguage('console')); ?>

<!-- meta -->

<?php echo Tag::meta()
	->init()
	->append('charset', 'utf-8')
	->append(['name' => 'viewport', 'content' => 'width=device-width'])
	->append(['name' => 'theme-color', 'content' => '#300a24'])
	->append(['name' => 'msapplication-navbutton-color', 'content' => '#300a24'])
	->append(['name' => 'apple-mobile-web-app-status-bar-stylecontent', 'content' => '#300a24']); ?>

<!-- link -->

<?php echo Tag::link()
	->init()
	->append(['href' => 'templates/default/assets/images/favicon.ico', 'rel' => 'shortcut icon'])
	->append(['href' => 'templates/default/assets/images/favicon.png', 'rel' => 'apple-touch-icon'])
	->appendFile(
	[
		'https://fonts.googleapis.com/css?family=Ubuntu+Mono:400&amp;subset=' . Helper::getSubset(),
		'templates/console/dist/styles/console.min.css'
	])
	->concat(); ?>

<!-- head script -->

<?php echo Tag::script()
	->init('head')
	->prependFile(
	[
		'templates/console/assets/scripts/init.js',
		'assets/scripts/init.js'
	])
	->transportVar('rs', Helper::getTransport())
	->concat();
?>
