<?php namespace Redaxscript\Template; ?>

<!DOCTYPE html>
<html lang="<?php echo Helper::getRegistry('language'); ?>" dir="<?php echo Helper::getDirection(); ?>" class="<?php echo Helper::getClass('rs-is-'); ?>">

	<!-- head -->

	<head>
		<?php echo Tag::partial('console/head.phtml'); ?>
	</head>

	<!-- body -->

	<body class="rs-body rs-console-body">

		<!-- main -->

		<main id="main" class="rs-console-main">
			<?php echo Tag::partial('console/content.phtml'); ?>
		</main>

		<!-- foot script -->

		<?php echo Tag::partial('console/script.phtml'); ?>
	</body>
</html>
