<p class="rs-admin-text-documentation">Syntax for your content:</p>

<pre class="rs-admin-js-code rs-admin-code-default html"><?php echo htmlspecialchars('<rs-module>
{
	"Gallery":
	{
		"directory": "images/gallery",
		"options":
		{
			"quality": 80,
			"height": 200
		}
	}
}
</rs-module>'); ?></pre>

<p class="rs-admin-text-documentation">Create thumbs on each request with reversed order:</p>

<pre class="rs-admin-js-code rs-admin-code-default html"><?php echo htmlspecialchars('<rs-module>
{
	"Gallery":
	{
		"directory": "images/gallery",
		"options":
		{
			"order": "desc",
			"command": "create"
		}
	}
}
</rs-module>'); ?></pre>

<p class="rs-admin-text-documentation">Remove thumbs on each request:</p>

<pre class="rs-admin-js-code rs-admin-code-default html"><?php echo htmlspecialchars('<rs-module>
{
	"Gallery":
	{
		"directory": "images/gallery",
		"options":
		{
			"command": "remove"
		}
	}
}
</rs-module>'); ?></pre>
