<p>Syntax for your content:</p>

<pre class="rs-admin-js-code rs-admin-code-default">&lt;module&gt;
{
	"Gallery":
	{
		"directory": "images/gallery",
		"options":
		{
			"quality": 80,
			"height": 200
		}
	}
}
&lt;/module&gt;</pre>

<p>Syntax to create thumbs on each page refresh with reversed order:</p>

<pre class="rs-admin-js-code rs-admin-code-default">&lt;module&gt;
{
	"Gallery":
	{
		"directory": "images/gallery",
		"options":
		{
			"order": "desc",
			"command": "create"
		}
	}
}
&lt;/module&gt;</pre>

<p>Syntax to remove thumbs:</p>

<pre class="rs-admin-js-code rs-admin-code-default">&lt;module&gt;
{
	"Gallery":
	{
		"directory": "images/gallery",
		"options":
		{
			"command": "remove"
		}
	}
}
&lt;/module&gt;</pre>