<p>Syntax for your content.</p>

<code class="js_code_quote box_code">&lt;function&gt;
{
	"gallery":
	{
		"directory": "images/gallery",
		"options":
		{
			"quality": 80,
			"height": 100
		}
	}
}
&lt;/function&gt;</code>

<p>Syntax to build thumbs on each page view with reversed order.</p>

<code class="js_code_quote box_code">&lt;function&gt;
{
	"gallery":
	{
		"directory": "images/gallery",
		"options":
		{
			"scaling": 80,
			"order": "desc"
		},
		"command": "build"
	}
}
&lt;/function&gt;</code>

<p>Syntax to delete thumbs directory.</p>

<code class="js_code_quote box_code">&lt;function&gt;
{
	"gallery":
	{
		"directory": "images/gallery",
		"command": "delete"
	}
}
&lt;/function&gt;</code>