<p>Syntax for your content:</p>

<pre class="js_code_quote box_code">&lt;module&gt;
{
	"Gallery":
	{
		"directory": "images/gallery",
		"options":
		{
			"quality": 80,
			"height": 100
		}
	}
}
&lt;/module&gt;</pre>

<p>Syntax to build thumbs on each page view with reversed order:</p>

<pre class="js_code_quote box_code">&lt;module&gt;
{
	"Gallery":
	{
		"directory": "images/gallery",
		"options":
		{
			"order": "desc",
			"command": "create"
		}
	}
}
&lt;/module&gt;</pre>

<p>Syntax to delete thumbs directory:</p>

<pre class="js_code_quote box_code">&lt;module&gt;
{
	"Gallery":
	{
		"directory": "images/gallery",
		"command": "remove"
	}
}
&lt;/module&gt;</pre>