<p>Syntax for your content:</p>

<pre class="rs-js-code-quote rs-box-code">&lt;function&gt;
{
	"gallery":
	{
		"directory": "images/gallery",
		"options":
		{
			"quality": 80,
			"height": 100
		}
	}
}
&lt;/function&gt;</pre>

<p>Syntax to build thumbs on each page view with reversed order:</p>

<pre class="rs-js-code-quote rs-box-code">&lt;function&gt;
{
	"gallery":
	{
		"directory": "images/gallery",
		"options":
		{
			"scaling": 80,
			"order": "desc"
		},
		"command": "build"
	}
}
&lt;/function&gt;</pre>

<p>Syntax to delete thumbs directory:</p>

<pre class="rs-js-code-quote rs-box-code">&lt;function&gt;
{
	"gallery":
	{
		"directory": "images/gallery",
		"command": "delete"
	}
}
&lt;/function&gt;</pre>