<?php namespace Redaxscript\Template; ?>

<p class="rs-admin-text-documentation">Browse <a href="<?php echo Helper::getRegistry('parameterRoute'); ?>module/feed-generator/articles" class="rs-admin-link-default">module/feed-generator/articles</a> and <a href="<?php echo Helper::getRegistry('parameterRoute'); ?>module/feed-generator/comments" class="rs-admin-link-default">module/feed-generator/comments</a> for generated atom feeds.</p>
