<p>Congratulations! Redaxscript has been successfully installed.</p>
<p>Redaxscript is a fast and simply full responsive CMS. It was designed and developed for people who care about simply and clean codebase.</p>
<img src="templates/default/assets/images/image_content.jpg" class="rs-image-default"/>
<h3 class="rs-title-sub">Advantages</h3>
<ul class="rs-list-default">
    <li>lightweight</li>
    <li>full responsive</li>
    <li>supports assetic management</li>
    <li>customizable via CASS</li>
</ul>
<blockquote class="rs-box-quote">Ultra lightweight Content Management System for MySQL, PostgreSQL and SQLite.</blockquote>