<blockquote class="rs-quote-default">Congratulations! Redaxscript has been successfully installed.</blockquote>

<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>

<svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 1200 400" class="rs-image-default">
	<rect height="400" width="1200" />
	<path d="M700,277.8V122.2c0-12.2-10-22.2-22.2-22.2H522.2c-12.2,0-22.2,10-22.2,22.2v155.6c0,12.2,10,22.2,22.2,22.2 h155.6C690,300,700,290,700,277.8z M561.1,216.7l27.8,33.4l38.9-50.1l50,66.7H522.2L561.1,216.7z" />
</svg>

<p>At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore.</p>

<rs-more>


<h3 class="rs-title-content-sub">Duo dolores</h3>

<ul class="rs-list-default">
	<li>Lorem ipsum dolor sit ame</li>
	<li>At vero eos et accusam</li>
	<li>Consetetur sadipscing elitr</li>
	<li>Dolores et ea rebum</li>
</ul>
