name: ci

on: [ push, pull_request ]

jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up PHP 7.4
    uses: shivammathur/setup-php@2.7.0
    with:
     php-version: 7.4
  - name: Set up Node 14
    uses: actions/setup-node@v1
    with:
     node-version: 14
  - run: composer install
  - run: npm install
  - run: grunt
 build:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up PHP 7.4
    uses: shivammathur/setup-php@2.9.0
    with:
     php-version: 7.4
  - name: Set up Node 14
    uses: actions/setup-node@v1
    with:
     node-version: 14
  - run: composer install
  - run: npm install
  - run: grunt build
 test-unit:
  runs-on: ubuntu-latest
  strategy:
   matrix:
    php-version: [ 7.2, 7.3, 7.4 ]
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up PHP ${{ matrix.php-version }}
    uses: shivammathur/setup-php@2.9.0
    with:
     php-version: ${{ matrix.php-version }}
  - run: sudo apt-get install sendmail
  - run: composer remove sebastian/phpcpd brianium/paratest --dev --no-update
    if: matrix.php-version < 7.4
  - run: composer require phpunit/phpunit 8.5.8 --dev --no-update
    if: matrix.php-version < 7.4
  - run: composer install
  - run: vendor/bin/phpunit
 test-acceptance:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up PHP 7.4
    uses: shivammathur/setup-php@2.9.0
    with:
     php-version: 7.4
  - name: Set up Node 14
    uses: actions/setup-node@v1
    with:
     node-version: 14
  - run: sudo apt-get install sendmail
  - run: composer install
  - run: npm install
  - run: grunt serve &
  - run: grunt test-acceptance
    env:
     CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
 report:
  needs: test-unit
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up PHP 7.4
    uses: shivammathur/setup-php@2.9.0
    with:
     php-version: 7.4
  - run: sudo apt-get install sendmail
  - run: composer require php-coveralls/php-coveralls 2.4.2 --dev --no-update
  - run: composer install
  - run: wget https://scrutinizer-ci.com/ocular.phar
  - run: vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
  - name: Report to Coveralls
    run: vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml
    env:
     COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  - name: Report to Scrutinizer
    run: php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
